Repository energywebfoundation/origin, pull requests merged in 2020-12, with the labels that each got.

#1758 chore: sync deps versions
  packages/exchange-client/package.json
  packages/exchange-ui-core/package.json
  packages/issuer-api-client/package.json
  packages/origin-backend-client/package.json
  packages/origin-backend/package.json
  packages/origin-organization-irec-api-client/package.json
  packages/origin-organization-irec-api/package.json
  yarn.lock
Labels: dependencies

#1759 fix: Updating User Profile
  packages/origin-backend/src/pods/user/dto/update-user-profile.dto.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
Labels: bug

#1764 chore(origin-backend): don't require grid operator on DTO level
  packages/origin-backend/src/pods/device/dto/create-device.dto.ts
Labels: bug

#1765 fix(exchange-ui-core): fix cancelling orders from the UI
  packages/exchange-ui-core/src/features/orders/sagas.ts
Labels: bug

#1762 UI fixes and improvements
  packages/localization/src/languages/en.json
  packages/localization/src/languages/pl.json
  packages/origin-ui-core/src/components/Account/Account.tsx
  packages/origin-ui-core/src/components/Modal/PendingInvitationsModal.tsx
  packages/origin-ui-core/src/components/Modal/UpdateSupplyModal.tsx
  packages/origin-ui-core/src/components/MultiSelectAutocomplete.tsx
  packages/origin-ui-core/src/components/Organization/Organization.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/components/devices/AutoSupplyDeviceTable.tsx
  packages/origin-ui-core/src/features/users/sagas.ts
Labels: bug

#1763 Release 4 Dec
  packages/exchange-client/package.json
  packages/exchange-ui-core/package.json
  packages/exchange-ui-core/src/features/orders/sagas.ts
  packages/issuer-api-client/package.json
  packages/localization/src/languages/en.json
  packages/localization/src/languages/pl.json
  packages/origin-backend-app/package.json
  packages/origin-backend-app/src/mail/mail.module.ts
  packages/origin-backend-app/src/mail/mail.service.ts
  packages/origin-backend-app/src/notification/handlers/registration-created.handler.ts
  packages/origin-backend-client/package.json
  packages/origin-backend-utils/src/guard/ActiveOrganizationGuard.ts
  packages/origin-backend/package.json
  packages/origin-backend/src/pods/device/dto/create-device.dto.ts
  packages/origin-backend/src/pods/user/dto/update-user-profile.dto.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-organization-irec-api-client/package.json
  packages/origin-organization-irec-api/package.json
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/components/IconPopover.tsx
  packages/origin-ui-core/src/components/Modal/PendingInvitationsModal.tsx
  packages/origin-ui-core/src/components/Modal/UpdateSupplyModal.tsx
  packages/origin-ui-core/src/components/MultiSelectAutocomplete.tsx
  packages/origin-ui-core/src/components/Organization/Organization.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/components/devices/AutoSupplyDeviceTable.tsx
  packages/origin-ui-core/src/features/users/actions.ts
  packages/origin-ui-core/src/features/users/sagas.ts
  yarn.lock
Labels: release

#1767 Release to master
  packages/device-registry/CHANGELOG.md
  packages/device-registry/package.json
  packages/exchange-client/CHANGELOG.md
  packages/exchange-client/package.json
  packages/exchange-ui-core/CHANGELOG.md
  packages/exchange-ui-core/package.json
  packages/exchange/CHANGELOG.md
  packages/exchange/package.json
  packages/issuer-api-client/CHANGELOG.md
  packages/issuer-api-client/package.json
  packages/issuer-api/CHANGELOG.md
  packages/issuer-api/package.json
  packages/localization/CHANGELOG.md
  packages/localization/package.json
  packages/origin-backend-app/CHANGELOG.md
  packages/origin-backend-app/package.json
  packages/origin-backend-client/CHANGELOG.md
  packages/origin-backend-client/package.json
  packages/origin-backend-utils/CHANGELOG.md
  packages/origin-backend-utils/package.json
  packages/origin-backend/CHANGELOG.md
  packages/origin-backend/package.json
  packages/origin-organization-irec-api-client/CHANGELOG.md
  packages/origin-organization-irec-api-client/package.json
  packages/origin-organization-irec-api/CHANGELOG.md
  packages/origin-organization-irec-api/package.json
  packages/origin-ui-core/CHANGELOG.md
  packages/origin-ui-core/package.json
  packages/origin-ui/CHANGELOG.md
  packages/origin-ui/package.json
  packages/solar-simulator/CHANGELOG.md
  packages/solar-simulator/package.json
Labels: release

#1768 chore: Change OrganizationStatus to be a stringed enum
  packages/migrations/config/seed.sql
  packages/origin-backend-app/src/notification/handlers/organization-status-changed.handler.ts
  packages/origin-backend-core/src/Organization.ts
  packages/origin-backend-utils/src/guard/ActiveOrganizationGuard.ts
  packages/origin-backend/migrations/1607081130178-OrganizationStatusesToString.ts
  packages/origin-backend/src/pods/organization/organization.entity.ts
  packages/origin-ui-core/src/components/Organization/OrganizationView.tsx
  packages/origin-ui-core/src/components/devices/DeviceMap.tsx
Labels: bug

#1824 chore: fix dependency issues on Heroku
  packages/exchange-io-erc1888/package.json
  packages/exchange/package.json
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/components/admin/Admin.tsx
  packages/origin-ui-core/src/components/admin/AdminUserView.tsx
  packages/origin-ui-core/src/components/admin/AdminUsersTable.tsx
  yarn.lock
Labels: bug

#1827 fix(exchange-core): Return assetId when cloning orders
  packages/exchange-core/src/Order.ts
  packages/exchange-irec/test/exchange.ts
  packages/exchange-irec/test/orderbook.e2e-spec.ts
Labels: bug
