Repository energywebfoundation/origin, pull requests merged in 2020-07, with the labels that each got.

#1227 chore: fix allowing users to use the app without MetaMask
  packages/localization/src/languages/en.json
  packages/origin-ui-core/src/components/AppContainer.tsx
  packages/origin-ui-core/src/components/Modal/NoBlockchainAccountModal.tsx
  packages/origin-ui-core/src/features/general/actions.ts
  packages/origin-ui-core/src/features/general/reducer.ts
  packages/origin-ui-core/src/features/general/sagas.ts
  packages/origin-ui-core/src/features/general/selectors.ts
  packages/origin-ui-core/src/utils/sagas/account.ts
Labels: bug

#1253 fix(origin-backend): only allow certain users to get user information
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/user.e2e-spec.ts
Labels: bug

#1255 fix(exchange): validity start/end date as string
  packages/exchange/src/pods/demand/demand-time-period.service.ts
Labels: bug

#1257 chore: improve device endpoints
  packages/device-registry/src/blockchain-facade/ProducingDevice.ts
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/origin-backend-client-mocks/src/DeviceClientMock.ts
  packages/origin-backend-client/src/AdminClient.ts
  packages/origin-backend-client/src/DeviceClient.ts
  packages/origin-backend-core/src/Device.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/solar-simulator/src/consumerService.ts
  packages/solar-simulator/src/workers/mockReadingsWorker.ts
Labels: bug, enhancement

#1279 fix(solar-simulator): saving smart meter readings
  packages/solar-simulator/src/consumerService.ts
  packages/solar-simulator/src/main.ts
  packages/solar-simulator/src/simulatorService.ts
  packages/solar-simulator/src/utils/Energy.ts
  packages/solar-simulator/src/utils/GeneratingDevice.ts
  packages/solar-simulator/src/workers/mockReadingsWorker.ts
Labels: bug

#1282 fix: Organization Permissions
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-ui-core/src/components/Organization/Organization.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationView.tsx
Labels: bug

#1288 feature/autorefresh store on cert action
  packages/origin-ui-core/src/components/CertificateTable.tsx
  packages/origin-ui-core/src/components/exchange/Exchange.tsx
  packages/origin-ui-core/src/features/certificates/actions.ts
  packages/origin-ui-core/src/features/certificates/reducer.ts
  packages/origin-ui-core/src/features/certificates/sagas.ts
  packages/origin-ui-core/src/features/general/sagas.ts
  packages/origin-ui-core/src/features/orders/sagas.ts
Labels: enhancement

#1287 feat: Email Confirmation
  packages/localization/src/languages/en.json
  packages/origin-backend-client-mocks/src/OffChainDataSourceMock.ts
  packages/origin-backend-client-mocks/src/UserClientMock.ts
  packages/origin-backend-client/src/UserClient.ts
  packages/origin-backend-core/src/EmailConfirmation.ts
  packages/origin-backend-core/src/Events.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend-core/src/index.ts
  packages/origin-backend/migrations/1594725219598-EmailConfirmation.ts
  packages/origin-backend/src/app.module.ts
  packages/origin-backend/src/index.ts
  packages/origin-backend/src/pods/email-confirmation/email-confirmation.entity.ts
  packages/origin-backend/src/pods/email-confirmation/email-confirmation.module.ts
  packages/origin-backend/src/pods/email-confirmation/email-confirmation.service.ts
  packages/origin-backend/src/pods/notification/EmailTypes.ts
  packages/origin-backend/src/pods/notification/notification.service.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.module.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/database.service.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
  packages/origin-backend/test/user.e2e-spec.ts
  packages/origin-ui-core/src/components/Account/Account.tsx
  packages/origin-ui-core/src/components/Account/ConfirmEmail.tsx
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/components/Modal/RemoveOrderConfirmation.tsx
  packages/origin-ui-core/src/components/PageContent/PageContent.tsx
Labels: enhancement

#1294 fix(origin-ui-core): Getting meter stats
  packages/origin-ui-core/src/components/ProducingDeviceTable.tsx
Labels: bug

#1292 fix(solar-simulator): Solar Simulator - change to worker
  packages/solar-simulator/Makefile
Labels: bug

#1299 fix(origin-ui-core): Getting reads in Device details view
  packages/origin-ui-core/src/components/ProducingDeviceDetailView.tsx
Labels: bug

#1298 fix(issuer): Certificate creation date always shows latest block timestamp
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/issuer/src/utils/events.ts
Labels: bug

#1316 chore: add support for a backup web3 node
  .env.example
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/exchange/src/pods/account-deployer/account-deployer.service.ts
  packages/exchange/src/pods/deposit-watcher/deposit-watcher.service.ts
  packages/exchange/src/pods/withdrawal-processor/withdrawal-processor.service.ts
  packages/exchange/test/exchange.ts
  packages/exchange/test/utils.ts
  packages/issuer/src/migrate.ts
  packages/issuer/src/test/Certificate.test.ts
  packages/issuer/src/test/Issuer.test.ts
  packages/migrations/package.json
  packages/migrations/src/deployContracts.ts
  packages/migrations/src/main.ts
  packages/origin-backend/src/pods/certificate/certificate-watcher.service.ts
  packages/origin-backend/src/pods/certificate/certificate.service.ts
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/features/general/sagas.ts
  packages/solar-simulator/src/consumerService.ts
  packages/solar-simulator/src/workers/mockReadingsWorker.ts
  packages/utils-general/src/blockchain-facade/Configuration.ts
  packages/utils-general/src/blockchain-facade/FallbackProvider.ts
  packages/utils-general/src/index.ts
Labels: enhancement

#1319 feat(origin-ui-core): UI Feature Flags
  packages/origin-ui-core/src/__tests__/unit/ProducingDeviceTable.test.tsx
  packages/origin-ui-core/src/__tests__/unit/SmartMeterReadingsChart.test.tsx
  packages/origin-ui-core/src/components/Account/Account.tsx
  packages/origin-ui-core/src/components/AppContainer.tsx
  packages/origin-ui-core/src/components/Header.tsx
  packages/origin-ui-core/src/components/OriginConfigurationContext.tsx
  packages/origin-ui-core/src/components/admin/Admin.tsx
  packages/origin-ui-core/src/components/admin/AdminUserForm.tsx
  packages/origin-ui-core/src/components/admin/AdminUserView.tsx
  packages/origin-ui-core/src/components/admin/AdminUsersTable.tsx
  packages/origin-ui-core/src/components/bundles/BundlesTable.tsx
  packages/origin-ui-core/src/components/certificates/CertificateDetailView.tsx
  packages/origin-ui-core/src/components/certificates/CertificateTable.tsx
  packages/origin-ui-core/src/components/certificates/Certificates.tsx
  packages/origin-ui-core/src/components/certificates/CertificationRequestsTable.tsx
  packages/origin-ui-core/src/components/devices/AddDevice.tsx
  packages/origin-ui-core/src/components/devices/AutoSupplyDeviceTable.tsx
  packages/origin-ui-core/src/components/devices/Device.tsx
  packages/origin-ui-core/src/components/devices/DeviceGroupForm.tsx
  packages/origin-ui-core/src/components/devices/DeviceMap.tsx
  packages/origin-ui-core/src/components/devices/DevicePermissionsFeedback.tsx
  packages/origin-ui-core/src/components/devices/DeviceSelectors.tsx
  packages/origin-ui-core/src/components/devices/ProducingDeviceDetailView.tsx
  packages/origin-ui-core/src/components/devices/ProducingDeviceTable.tsx
  packages/origin-ui-core/src/components/devices/SmartMeterReadingsChart.tsx
  packages/origin-ui-core/src/components/devices/SmartMeterReadingsTable.tsx
  packages/origin-ui-core/src/components/exchange/Market.tsx
  packages/origin-ui-core/src/components/index.ts
  packages/origin-ui-core/src/components/route/FeatureRoute.tsx
  packages/origin-ui-core/src/utils/helper.ts
  packages/origin-ui-core/src/utils/routing.ts
  packages/utils-general/src/OriginFeature.ts
  packages/utils-general/src/index.ts
Labels: enhancement

#1323 chore: export individual NestJS modules
  packages/exchange/src/app.module.ts
  packages/exchange/src/index.ts
  packages/origin-backend/src/app.module.ts
  packages/origin-backend/src/index.ts
Labels: dependencies

#1334 bug(origin-ui-core): no invitation for unregistered user
  packages/origin-backend/src/pods/organization/organization.controller.ts
Labels: bug

#1343 bug(exchange): validation is not working
  packages/exchange/src/pods/bundle/create-bundle.dto.ts
  packages/exchange/src/pods/demand/create-demand.dto.ts
  packages/exchange/src/pods/order/create-bid.dto.ts
  packages/exchange/src/pods/order/product.dto.ts
  packages/exchange/test/bundles.e2e-spec.ts
Labels: bug
