Repository energywebfoundation/origin, pull requests merged in 2020-04, with the labels that each got.

#763 Exchange based demands
  packages/exchange-core/src/Demand.ts
  packages/exchange-core/src/index.ts
  packages/exchange/package.json
  packages/exchange/src/pods/demand/create-demand.dto.ts
  packages/exchange/src/pods/demand/demand.controller.ts
  packages/exchange/src/pods/demand/demand.entity.ts
  packages/exchange/src/pods/demand/demand.service.ts
  packages/exchange/src/pods/matching-engine/matching-engine.module.ts
  packages/exchange/src/pods/matching-engine/matching-engine.service.ts
  packages/exchange/src/pods/order/create-ask.dto.ts
  packages/exchange/src/pods/order/create-bid.dto.ts
  packages/exchange/src/pods/order/order.controller.ts
  packages/exchange/src/pods/order/order.module.ts
  packages/exchange/src/pods/order/order.service.ts
  packages/exchange/src/utils/exceptions.ts
  packages/exchange/test/api-orders.e2e-spec.ts
  packages/exchange/test/demand.e2e-spec.ts
  packages/exchange/test/direct-buy.e2e-spec.ts
  packages/exchange/test/exchange.ts
  packages/utils-general/src/blockchain-facade/EnumExports.ts
  packages/utils-general/src/index.ts
Labels: enhancement

#769 Use test keys in .env.example
  .env.example
Labels: documentation

#772 chore(migrations): include configs in the NPM release
  packages/migrations/package.json
  packages/migrations/src/main.ts
  packages/migrations/src/schema/create_tables.sql
Labels: bug

#777 Exchange API validators
  packages/exchange/src/app.module.ts
  packages/exchange/src/pods/matching-engine/matching-engine.module.ts
  packages/exchange/src/pods/matching-engine/matching-engine.service.ts
  packages/exchange/src/pods/order-book/order-book.controller.ts
  packages/exchange/src/pods/order-book/order-book.module.ts
  packages/exchange/src/pods/order-book/product-filter.dto.ts
  packages/exchange/src/pods/order/product.dto.ts
  packages/exchange/src/pods/runner/deviceTypeServiceWrapper.ts
  packages/exchange/src/pods/runner/index.ts
  packages/exchange/src/pods/runner/runner.module.ts
  packages/exchange/src/pods/runner/runner.service.ts
  packages/exchange/src/utils/deviceTypeValidator.ts
  packages/exchange/src/utils/filterValidator.ts
  packages/exchange/src/utils/httpLoggingInterceptor.ts
  packages/exchange/test/exchange.ts
  packages/exchange/test/orderbook.e2e-spec.ts
  packages/origin-backend-app/package.json
  packages/origin-backend-app/src/main.ts
Labels: bug

#779 fix(migrations): set next autoincrement ID after SQL seeding
  packages/migrations/config/seed.sql
  packages/migrations/src/main.ts
  packages/migrations/src/schema/create_tables.sql
Labels: bug

#780 fix(exchange): public order book endpoint
  packages/exchange/src/pods/order-book/order-book.controller.ts
Labels: bug

#796 chore: update fs-extra to v9
  packages/device-registry/package.json
  packages/issuer/package.json
  packages/solar-simulator/package.json
  packages/utils-general/package.json
  yarn.lock
Labels: dependencies

#851 TypeORM migrations
  package.json
  packages/exchange/README.md
  packages/exchange/bin/origin-exchange-migrate
  packages/exchange/migrations/1586949939455-Initial.ts
  packages/exchange/migrations/1586956731982-InitialUsingTypeOrm.ts
  packages/exchange/migrations/initial.sql
  packages/exchange/ormconfig-dev.ts
  packages/exchange/ormconfig.ts
  packages/exchange/package.json
  packages/exchange/src/app.module.ts
  packages/exchange/src/main-dev.ts
  packages/exchange/src/main.ts
  packages/exchange/tsconfig.build.json
  packages/migrations/README.md
  packages/migrations/deployment/migrations/canary/Dockerfile
  packages/migrations/package.json
  packages/migrations/src/main.ts
  packages/migrations/src/schema/create_tables.sql
  packages/migrations/src/schema/drop_schema.sql
  packages/origin-backend-app/README.md
  packages/origin-backend/bin/origin-backend-migrate
  packages/origin-backend/migrations/1586949939455-Initial.ts
  packages/origin-backend/migrations/1586960951326-InitialUsingTypeOrm.ts
  packages/origin-backend/migrations/initial.sql
  packages/origin-backend/ormconfig-dev.ts
  packages/origin-backend/ormconfig.ts
  packages/origin-backend/package.json
  packages/origin-backend/readme.md
  packages/origin-backend/tsconfig.build.json
Labels: enhancement

#857 chore(origin-backend-app): print package version on start
  packages/origin-backend-app/src/main.ts
Labels: documentation

#864 fix(issuer): contract interactions wait
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/migrate.ts
Labels: bug

#888 feat: required device external IDs
  packages/origin-backend-core/src/Device.ts
  packages/origin-ui-core/src/components/AddDevice.tsx
  packages/origin-ui-core/src/components/DeviceGroupForm.tsx
Labels: enhancement

#861 feat(origin-backend-app): enable swagger endpoint
  packages/origin-backend-app/nest-cli.json
  packages/origin-backend-app/package.json
  packages/origin-backend-app/src/main.ts
Labels: work in progress

#895 Fix: CertificationRequest backend data unavailable
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/origin-ui-core/src/components/CertificationRequestsTable.tsx
  packages/origin-ui-core/src/features/general/sagas.ts
  yarn.lock
Labels: bug

#897 fix(exchange-core): fix matching termination
  packages/exchange-core/src/MatchingEngine.ts
  packages/exchange-core/src/test/Matching.test.ts
Labels: bug

#899 fix(origin-ui-core): fix showing values lower than 1 MWh on smart met…
  packages/origin-ui-core/src/__tests__/unit/ProducingDeviceTable.test.tsx
  packages/origin-ui-core/src/__tests__/unit/SmartMeterReadingsChart.test.tsx
  packages/origin-ui-core/src/components/Modal/PublishForSaleModal.tsx
  packages/origin-ui-core/src/components/Modal/RequestCertificatesModal.tsx
  packages/origin-ui-core/src/components/exchange/Asks.tsx
  packages/origin-ui-core/src/utils/EnergyFormatter.ts
Labels: bug

#902 fix(exchange): generation times parsing
  packages/exchange/src/pods/deposit-watcher/deposit-watcher.service.ts
  packages/exchange/src/pods/order/order.service.ts
  packages/exchange/test/api-orders.e2e-spec.ts
  packages/exchange/test/deposits-withdrawals.e2e-spec.ts
Labels: bug

#905 fix(issuer): swtich IDs to get correct certificationRequestId in Cert…
  packages/issuer/src/blockchain-facade/Certificate.ts
Labels: bug

#908 chore(issuer): improved fetching certificates
  packages/issuer/contracts/Issuer.sol
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/test/Issuer.test.ts
Labels: enhancement

#909 fix(origin-ui-core): certificates not resyncing after user change
  packages/origin-ui-core/src/features/general/sagas.ts
Labels: bug

#911 fix(origin-ui-core): putting a NaN in request amount crashes site
  packages/origin-ui-core/src/components/Modal/RequestCertificatesModal.tsx
Labels: bug

#912 fix: certificate history
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/origin-ui-core/src/components/CertificateDetailView.tsx
Labels: bug

#943 chore: rm unused deps ws and axios
  packages/origin-backend-app/package.json
  packages/origin-backend-client/package.json
  packages/origin-backend/package.json
Labels: dependencies

#946 fix(origin-backend): migration dropping column
  packages/origin-backend/migrations/1587979261608-DefaultAskPriceColumnInDevice.ts
Labels: bug
