Repository energywebfoundation/origin, pull requests merged in 2020-06, with the labels that each got.

#1094 Change Organization Member Role
  packages/migrations/config/seed.sql
  packages/origin-backend-client-mocks/src/OrganizationClientMock.ts
  packages/origin-backend-client/src/OrganizationClient.ts
  packages/origin-backend-core/src/Events.ts
  packages/origin-backend-core/src/Organization.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend/migrations/1590748428468-RmLeadUser.ts
  packages/origin-backend/src/pods/notification/EmailTypes.ts
  packages/origin-backend/src/pods/notification/notification.service.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.entity.ts
  packages/origin-backend/src/pods/organization/organization.service.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-ui-core/src/components/Modal/ChangeRoleModal.tsx
  packages/origin-ui-core/src/components/Organization/Organization.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvitations.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/features/users/selectors.ts
Labels: enhancement

#1115 fix(origin-ui-core): show asks in device timezone
  packages/origin-ui-core/src/components/CertificateTable.tsx
  packages/origin-ui-core/src/components/exchange/Asks.tsx
Labels: bug

#1119 chore(origin-ui-core): lower exchange refresh from 5 to 3 sec
  packages/origin-ui-core/src/components/exchange/Exchange.tsx
Labels: enhancement

#1117 chore: improved direct buy
  .env.example
  packages/exchange-core/src/Order.ts
  packages/exchange/src/pods/demand/demand.service.ts
  packages/exchange/src/pods/matching-engine/matching-engine.service.ts
  packages/exchange/src/pods/order/order-status.enum.ts
  packages/exchange/src/pods/order/order.entity.ts
  packages/exchange/src/pods/order/order.service.ts
  packages/exchange/src/pods/trade/trade.service.ts
  packages/exchange/test/api-orders.e2e-spec.ts
  packages/exchange/test/demand.e2e-spec.ts
  packages/exchange/test/deposits-auto-post-for-sale.e2e-spec.ts
  packages/origin-ui-core/src/components/exchange/Exchange.tsx
  packages/origin-ui-core/src/utils/exchange/ExchangeClient.ts
  packages/origin-ui-core/src/utils/exchange/types.ts
Labels: bug

#1122 fix(origin-ui-core): resync certificate after posting for sale
  packages/origin-ui-core/src/components/Modal/PublishForSaleModal.tsx
  packages/origin-ui-core/src/features/certificates/actions.ts
  packages/origin-ui-core/src/features/certificates/sagas.ts
  packages/origin-ui-core/src/features/general/sagas.ts
Labels: bug

#1124 fix(exchange): wrong TradePersistedEvent type emit
  packages/exchange/src/pods/trade/trade.service.ts
Labels: bug

#1123 fix: Certification Request off-chain data queue
  packages/device-registry/package.json
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client/src/CertificateClient.ts
  packages/origin-backend-core/src/CertificationRequest.ts
  packages/origin-backend/.env.test
  packages/origin-backend/migrations/1591277300788-CertificationRequestQueue.ts
  packages/origin-backend/src/index.ts
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certificate.module.ts
  packages/origin-backend/src/pods/certificate/certification-request-queue-item.dto.ts
  packages/origin-backend/src/pods/certificate/certification-request-queue-item.entity.ts
  packages/origin-backend/src/pods/certificate/certification-request.dto.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
  packages/origin-backend/src/pods/certificate/index.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  yarn.lock
Labels: bug, enhancement

#1144 chore: not logged in feedback
  packages/localization/src/languages/en.json
  packages/origin-ui-core/src/components/Organization/OrganizationInvitations.tsx
Labels: bug

#1147 fix(origin-backend): Certification Request energy & files not nullable
  packages/origin-backend/migrations/1591774915665-CertificationRequestEnergyFilesNotNull.ts
  packages/origin-backend/src/pods/certificate/certification-request-queue-item.entity.ts
  packages/origin-backend/src/pods/certificate/certification-request.entity.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
Labels: bug

#1148 fix(origin-backend): combine notNull default
  packages/origin-backend/migrations/1591774915665-CertificationRequestEnergyFilesNotNull.ts
Labels: bug

#1149 fix(origin-backend): syntax not null and default
  packages/origin-backend/migrations/1591774915665-CertificationRequestEnergyFilesNotNull.ts
Labels: bug

#1150 fix(migrations): make the Issuer user automatically Active
  packages/migrations/config/seed.sql
Labels: bug

#1152 chore: move Certification Request validation to the backend
  packages/issuer/package.json
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/origin-backend-client-mocks/package.json
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client-mocks/src/OrganizationClientMock.ts
  packages/origin-backend-client/src/CertificateClient.ts
  packages/origin-backend-client/src/OrganizationClient.ts
  packages/origin-backend-core/src/CertificationRequest.ts
  packages/origin-backend-core/src/General.ts
  packages/origin-backend-core/src/Organization.ts
  packages/origin-backend-core/src/OrganizationInvitation.ts
  packages/origin-backend/package.json
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
  packages/origin-backend/src/pods/organization/organization-invitation.service.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-ui-core/src/features/certificates/sagas.ts
Labels: enhancement

#1155 fix(origin-backend): fix updating device
  packages/origin-backend/src/pods/device/device.service.ts
Labels: bug

#1156 chore: only pull device.meterStats when explicitly requested
  packages/device-registry/src/blockchain-facade/ProducingDevice.ts
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/origin-backend-client-mocks/src/DeviceClientMock.ts
  packages/origin-backend-client/src/DeviceClient.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-ui-core/src/components/AutoSupplyDeviceTable.tsx
  packages/origin-ui-core/src/features/general/sagas.ts
Labels: enhancement

#1175 chore(origin-ui-core): remove Delete option on Supply table
  packages/origin-ui-core/src/components/AutoSupplyDeviceTable.tsx
Labels: bug

#1174 chore(origin-ui-core): Localize Certificate logs and add more info
  .env.example
  packages/localization/src/languages/en.json
  packages/origin-ui-core/env.sh
  packages/origin-ui-core/src/components/CertificateDetailView.tsx
  packages/origin-ui-core/src/features/general/actions.ts
Labels: enhancement

#1176 chore: show correct energy values in certificate details and table
  packages/localization/src/languages/en.json
  packages/origin-ui-core/src/components/CertificateDetailView.tsx
  packages/origin-ui-core/src/components/CertificateTable.tsx
  packages/origin-ui-core/src/components/Certificates.tsx
Labels: bug

#1179 Fixes: Admin Table
  packages/exchange/test/exchange.ts
  packages/localization/src/languages/en.json
  packages/migrations/config/seed.sql
  packages/origin-backend-client-mocks/src/UserClientMock.ts
  packages/origin-backend-client/src/AdminClient.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend-utils/src/guard/ActiveUserGuard.ts
  packages/origin-backend/src/pods/admin/admin.controller.ts
  packages/origin-backend/src/pods/admin/admin.module.ts
  packages/origin-backend/src/pods/admin/admin.service.ts
  packages/origin-backend/src/pods/admin/index.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.entity.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/certificate.e2e-spec.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
  packages/origin-backend/test/user.e2e-spec.ts
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/components/AdminUserForm.tsx
  packages/origin-ui-core/src/components/AdminUsersTable.tsx
  packages/origin-ui-core/src/components/CertificationRequestsTable.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/components/Table/IndividualFilter.tsx
  packages/origin-ui-core/src/features/certificates/sagas.ts
  packages/origin-ui-core/src/utils/device.ts
Labels: bug

#1205 chore: Optimize CertificationRequest syncing
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/test/Issuer.test.ts
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client/src/CertificateClient.ts
  packages/origin-ui-core/src/components/CertificateDetailView.tsx
  packages/origin-ui-core/src/components/CertificationRequestsTable.tsx
Labels: bug

#1225 fix: UI url when provisioning Heroku
  provision-heroku-origin.sh
Labels: bug

#1224 chore: move Google Maps API key from code to .env
  .env.example
  packages/origin-ui-core/env.sh
  packages/origin-ui-core/src/components/DeviceMap.tsx
  packages/origin-ui-core/src/components/GoogleApiKey.tsx
  packages/origin-ui-core/src/features/general/actions.ts
Labels: bug

#1223 fix: Show proper user status name, instead of integer number
  packages/localization/src/languages/en.json
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
Labels: bug
