Repository energywebfoundation/origin, pull requests merged in 2020-11, with the labels that each got.

#1669 chore: add .idea to .gitignore
  .gitignore
Labels: good first issue

#1697 chore(origin-ui-core): Certificate Details - Energy fix
  packages/origin-ui-core/src/components/certificates/CertificateDetailView.tsx
Labels: bug

#1696 chore(issuer-api): Sync discrepancies watcher
  packages/issuer-api/package.json
  packages/issuer-api/src/app.module.ts
  packages/issuer-api/src/pods/certification-request/certification-request.module.ts
  packages/issuer-api/src/pods/certification-request/sync-certification-request.task.ts
  packages/origin-ui/.prettierignore
  packages/origin-ui/src/styles/app.scss
Labels: bug

#1699 fix(origin-ui-core): Fetch exchange certificates using tokenId
  packages/origin-ui-core/src/features/certificates/sagas.ts
  packages/origin-ui-core/src/features/general/sagas.ts
Labels: bug

#1700 fix(origin-ui): typo on running node --max-old-space-size=8192
  packages/origin-ui/package.json
Labels: bug

#1698 fix(issuer-api): Return correct HTTP status codes
  packages/issuer-api/src/pods/certificate/certificate.controller.ts
  packages/issuer-api/src/pods/certificate/handlers/bulk-claim-certificates.handler.ts
  packages/issuer-api/src/pods/certificate/handlers/certificate-created.handler.ts
  packages/issuer-api/src/pods/certificate/handlers/claim-certificate.handler.ts
  packages/issuer-api/src/pods/certificate/handlers/sync-certificate.handler.ts
  packages/issuer-api/src/pods/certificate/handlers/transfer-certificate.handler.ts
  packages/issuer-api/src/pods/certification-request/certification-request.controller.ts
  packages/issuer-api/src/pods/certification-request/handlers/approve-certification-request.handler.ts
  packages/issuer-api/src/pods/certification-request/handlers/certificate-bound-to-certification-request.handler.ts
  packages/issuer-api/src/pods/certification-request/handlers/revoke-certification-request.handler.ts
  packages/issuer-api/src/pods/certification-request/handlers/validate-certification-request.handler.ts
  packages/issuer-api/test/certification-request.e2e-spec.ts
  packages/origin-backend-core/src/General.ts
  packages/origin-backend-utils/index.ts
  packages/origin-backend-utils/src/interceptor/ExceptionInterceptor.ts
Labels: bug

#1703 feat(origin-ui-core): MetaMask transfers and claims
  packages/issuer-api/src/pods/blockchain/blockchain-properties.controller.ts
  packages/issuer-api/src/pods/blockchain/blockchain-properties.dto.ts
  packages/issuer-api/src/pods/blockchain/blockchain-properties.module.ts
  packages/issuer-api/src/pods/blockchain/blockchain-properties.service.ts
  packages/issuer-api/test/blockchain-properties.e2e-spec.ts
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/origin-ui-core/src/features/certificates/actions.ts
  packages/origin-ui-core/src/features/certificates/reducer.ts
  packages/origin-ui-core/src/features/certificates/sagas.ts
  packages/origin-ui-core/src/features/certificates/selectors.ts
  packages/origin-ui-core/src/features/general/sagas.ts
  packages/origin-ui-core/src/features/users/sagas.ts
Labels: enhancement

#1719 Create pull_request_template.md
  doc/pull_request_template.md
Labels: documentation

#1726 fix(origin-ui-core): Use token Id when filtering exchange certificates
  packages/origin-ui-core/src/features/general/sagas.ts
Labels: bug

#1727 Orderbook endpoint
  packages/exchange-ui-core/src/components/exchange/Asks.tsx
  packages/exchange-ui-core/src/containers/Exchange.tsx
  packages/exchange-ui-core/src/features/general/sagas.ts
  packages/exchange-ui-core/src/utils/exchange/ExchangeClient.ts
  packages/origin-ui-core/src/components/Modal/LoginNoInvitationsModal.tsx
Labels: bug

#1730 Branch release to master
  packages/device-registry/CHANGELOG.md
  packages/device-registry/package.json
  packages/exchange-core/CHANGELOG.md
  packages/exchange-core/package.json
  packages/exchange-token-account/CHANGELOG.md
  packages/exchange-token-account/package.json
  packages/exchange-ui-core/CHANGELOG.md
  packages/exchange-ui-core/package.json
  packages/exchange/CHANGELOG.md
  packages/exchange/package.json
  packages/issuer-api-client/CHANGELOG.md
  packages/issuer-api-client/package.json
  packages/issuer-api/CHANGELOG.md
  packages/issuer-api/package.json
  packages/issuer-irec-api-wrapper/CHANGELOG.md
  packages/issuer-irec-api-wrapper/package.json
  packages/issuer/CHANGELOG.md
  packages/issuer/package.json
  packages/localization/CHANGELOG.md
  packages/localization/package.json
  packages/migrations/CHANGELOG.md
  packages/migrations/package.json
  packages/origin-backend-app/CHANGELOG.md
  packages/origin-backend-app/package.json
  packages/origin-backend-client-mocks/CHANGELOG.md
  packages/origin-backend-client-mocks/package.json
  packages/origin-backend-client/CHANGELOG.md
  packages/origin-backend-client/package.json
  packages/origin-backend-core/CHANGELOG.md
  packages/origin-backend-core/package.json
  packages/origin-backend-utils/CHANGELOG.md
  packages/origin-backend-utils/package.json
  packages/origin-backend/CHANGELOG.md
  packages/origin-backend/package.json
  packages/origin-organization-irec-api/CHANGELOG.md
  packages/origin-organization-irec-api/package.json
  packages/origin-ui-core/CHANGELOG.md
  packages/origin-ui-core/package.json
  packages/origin-ui/CHANGELOG.md
  packages/origin-ui/package.json
  packages/solar-simulator/CHANGELOG.md
  packages/solar-simulator/package.json
  packages/utils-general/CHANGELOG.md
  packages/utils-general/package.json
Labels: documentation

#1736 chore(issuer): move encode/decode claim data to Issuer.sol
  packages/issuer/contracts/Issuer.sol
  packages/issuer/contracts/Registry.sol
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
Labels: bug

#1740 chore(issuer-api): use correct type for Registry contract
  packages/issuer-api/src/pods/certificate/listeners/on-chain-certificates.listener.ts
Labels: bug

#1743 fix: Device Creation
  packages/device-registry/src/blockchain-facade/ProducingDevice.ts
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/origin-backend-core/src/Device.ts
  packages/origin-backend/src/pods/device/create-device.dto.ts
  packages/origin-backend/src/pods/device/device-settings-update.dto.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.dto.ts
  packages/origin-backend/src/pods/device/device.entity.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-ui-core/src/components/devices/AddDevice.tsx
  packages/origin-ui-core/src/components/devices/DeviceGroupForm.tsx
Labels: bug

#1744 fix: add a body definition to all missing @Body() in requests
  packages/exchange/src/pods/bundle/bundle.controller.ts
  packages/exchange/src/pods/demand/demand.controller.ts
  packages/exchange/src/pods/order-book/order-book.controller.ts
  packages/exchange/src/pods/order/order.controller.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend/src/pods/admin/admin.controller.ts
  packages/origin-backend/src/pods/invitation/invitation.controller.ts
  packages/origin-backend/src/pods/invitation/invite.dto.ts
  packages/origin-backend/src/pods/organization/organization-update-member.dto.ts
  packages/origin-backend/src/pods/organization/organization-update.dto.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/user/register-user.dto.ts
  packages/origin-backend/src/pods/user/update-blockchain-address.dto.ts
  packages/origin-backend/src/pods/user/update-password.dto.ts
  packages/origin-backend/src/pods/user/update-user.dto.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/invitation.e2e-spec.ts
  packages/origin-organization-irec-api/src/registration/registration.controller.ts
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/components/Modal/ChangeRoleModal.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
Labels: bug

#1746 fix: Make DeviceStatus enum a string
  packages/migrations/config/seed.sql
  packages/origin-backend-core/src/Device.ts
  packages/origin-backend/migrations/1606382412522-DeviceStatusToString.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.entity.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/src/pods/device/dto/create-device.dto.ts
  packages/origin-backend/src/pods/device/dto/device-settings-update.dto.ts
  packages/origin-backend/src/pods/device/dto/device.dto.ts
  packages/origin-backend/src/pods/device/dto/external-device-id.dto.ts
  packages/origin-backend/src/pods/device/dto/smart-meter-readings.dto.ts
  packages/origin-backend/src/pods/device/dto/smart-meter-stats.dto.ts
  packages/origin-backend/src/pods/device/dto/update-device-status.dto.ts
Labels: bug

#1747 fix: Organization Invitations and changing user roles
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/invitation/invitation.controller.ts
  packages/origin-backend/src/pods/invitation/invitation.dto.ts
  packages/origin-backend/src/pods/invitation/invitation.entity.ts
  packages/origin-backend/src/pods/invitation/invite.dto.ts
  packages/origin-backend/src/pods/organization/dto/full-organization-info.dto.ts
  packages/origin-backend/src/pods/organization/dto/new-organization.dto.ts
  packages/origin-backend/src/pods/organization/dto/organization-invitation.dto.ts
  packages/origin-backend/src/pods/organization/dto/organization-update-member.dto.ts
  packages/origin-backend/src/pods/organization/dto/organization-update.dto.ts
  packages/origin-backend/src/pods/organization/dto/public-organization-info.dto.ts
  packages/origin-backend/src/pods/organization/index.ts
  packages/origin-backend/src/pods/organization/organization-update-member.dto.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.service.ts
  packages/origin-backend/test/invitation.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
  packages/origin-ui-core/src/components/Modal/ChangeRoleModal.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvitationTable.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
Labels: bug

#1749 Fix: Demand Creation
  packages/exchange-ui-core/src/components/Form/CalendarFieldOnPeriod.tsx
  packages/exchange-ui-core/src/components/exchange/Market.tsx
  packages/exchange-ui-core/src/components/modal/DemandUpdateModal.tsx
  packages/exchange-ui-core/src/containers/Exchange.tsx
  packages/exchange-ui-core/src/containers/MyOrders.tsx
  packages/exchange-ui-core/src/features/orders/actions.ts
  packages/exchange-ui-core/src/features/orders/sagas.ts
  packages/exchange-ui-core/src/utils/demand/period.ts
  packages/exchange-ui-core/src/utils/demand/status.ts
  packages/exchange-ui-core/src/utils/exchange/math.ts
  packages/exchange-ui-core/src/utils/exchange/types.ts
  packages/exchange/migrations/1606405724791-DemandUpdates.ts
  packages/exchange/src/pods/demand/demand-time-period.service.spec.ts
  packages/exchange/src/pods/demand/demand-time-period.service.ts
  packages/exchange/src/pods/demand/demand.entity.ts
  packages/exchange/test/demand.e2e-spec.ts
  packages/origin-ui-core/src/components/Form/CalendarFieldOnPeriod.tsx
  packages/origin-ui-core/src/utils/exchange/math.ts
  packages/origin-ui-core/src/utils/exchange/types.ts
  packages/utils-general/src/blockchain-facade/EnumExports.ts
Labels: bug

#1750 chore: Explicit @Query definitions
  packages/exchange/src/pods/demand/demand.service.ts
  packages/migrations/config/seed.sql
  packages/origin-backend-app/src/notification/handlers/device-status-changed.handler.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend-utils/src/guard/ActiveUserGuard.ts
  packages/origin-backend-utils/src/guard/NotDeletedUserGuard.ts
  packages/origin-backend/migrations/1606471100149-UserStatusesToString.ts
  packages/origin-backend/src/pods/admin/admin.controller.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/user/dto/register-user.dto.ts
  packages/origin-backend/src/pods/user/dto/update-blockchain-address.dto.ts
  packages/origin-backend/src/pods/user/dto/update-own-user.dto.ts
  packages/origin-backend/src/pods/user/dto/update-password.dto.ts
  packages/origin-backend/src/pods/user/dto/update-user.dto.ts
  packages/origin-backend/src/pods/user/dto/user.dto.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.entity.ts
  packages/origin-ui-core/src/components/Account/UserProfile.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
  packages/origin-ui-core/src/components/Organization/OrganizationUsersTable.tsx
  packages/origin-ui-core/src/components/admin/AdminUserForm.tsx
  packages/origin-ui-core/src/components/admin/AdminUsersTable.tsx
  packages/origin-ui-core/src/components/certificates/CertificationRequestsTable.tsx
  packages/origin-ui-core/src/components/devices/AutoSupplyDeviceTable.tsx
  packages/origin-ui-core/src/components/devices/ProducingDeviceTable.tsx
Labels: bug

#1754 fix(origin-backend): fix issue where controller returns empty org inv…
  packages/origin-backend/src/pods/invitation/invitation.dto.ts
  packages/origin-backend/src/pods/organization/dto/organization-invitation.dto.ts
  packages/origin-backend/src/pods/organization/index.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/test/organization.e2e-spec.ts
Labels: bug

#1756 Release to master
  packages/device-registry/CHANGELOG.md
  packages/device-registry/package.json
  packages/exchange-client/CHANGELOG.md
  packages/exchange-client/package.json
  packages/exchange-core/CHANGELOG.md
  packages/exchange-core/package.json
  packages/exchange-token-account/CHANGELOG.md
  packages/exchange-token-account/package.json
  packages/exchange-ui-core/CHANGELOG.md
  packages/exchange-ui-core/package.json
  packages/exchange/CHANGELOG.md
  packages/exchange/package.json
  packages/issuer-api-client/CHANGELOG.md
  packages/issuer-api-client/package.json
  packages/issuer-api/CHANGELOG.md
  packages/issuer-api/package.json
  packages/issuer-irec-api-wrapper/CHANGELOG.md
  packages/issuer-irec-api-wrapper/package.json
  packages/issuer/CHANGELOG.md
  packages/issuer/package.json
  packages/localization/CHANGELOG.md
  packages/localization/package.json
  packages/migrations/CHANGELOG.md
  packages/migrations/package.json
  packages/origin-backend-app/CHANGELOG.md
  packages/origin-backend-app/package.json
  packages/origin-backend-client/CHANGELOG.md
  packages/origin-backend-client/package.json
  packages/origin-backend-core/CHANGELOG.md
  packages/origin-backend-core/package.json
  packages/origin-backend-utils/CHANGELOG.md
  packages/origin-backend-utils/package.json
  packages/origin-backend/CHANGELOG.md
  packages/origin-backend/package.json
  packages/origin-organization-irec-api-client/CHANGELOG.md
  packages/origin-organization-irec-api-client/package.json
  packages/origin-organization-irec-api/CHANGELOG.md
  packages/origin-organization-irec-api/package.json
  packages/origin-ui-core/CHANGELOG.md
  packages/origin-ui-core/package.json
  packages/origin-ui/CHANGELOG.md
  packages/origin-ui/package.json
  packages/solar-simulator/CHANGELOG.md
  packages/solar-simulator/package.json
  packages/utils-general/CHANGELOG.md
  packages/utils-general/package.json
  yarn.lock
Labels: release
