Repository energywebfoundation/origin, pull requests merged in 2020-05, with the labels that each got.

#972 chore: rm reference to sqlite
  .dockerignore
  .gitignore
  packages/device-registry/.gitignore
  packages/device-registry/package.json
  packages/exchange-core/package.json
  packages/issuer/.gitignore
  packages/origin-backend-app/package.json
  packages/origin-backend/package.json
  packages/origin-ui-core/.eslintignore
  packages/origin-ui-core/.gitignore
  packages/origin-ui/.eslintignore
  packages/origin-ui/.gitignore
  packages/solar-simulator/.gitignore
  yarn.lock
Labels: dependencies

#915 Bind CertificationRequests to Device
  packages/issuer/package.json
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/index.ts
  packages/issuer/src/test/Issuer.test.ts
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client/src/CertificateClient.ts
  packages/origin-backend-core/src/CertificationRequest.ts
  packages/origin-backend/.env.test
  packages/origin-backend/migrations/1588586888481-CertificationRequestFull.ts
  packages/origin-backend/package.json
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certificate.module.ts
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
  packages/origin-backend/src/pods/certificate/certification-request.dto.ts
  packages/origin-backend/src/pods/certificate/certification-request.entity.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.entity.ts
  packages/origin-backend/src/pods/device/device.module.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/src/pods/device/index.ts
  packages/origin-backend/src/pods/organization/index.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.module.ts
  packages/origin-backend/src/pods/organization/organization.service.ts
  packages/origin-backend/src/pods/user/user.module.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
  packages/origin-ui-core/src/components/CertificationRequestsTable.tsx
  packages/utils-general/src/Signing.ts
  yarn.lock
Labels: enhancement

#974 Organizations overhaul
  packages/exchange/package.json
  packages/exchange/src/pods/account/account.controller.ts
  packages/exchange/src/pods/decorators/user.decorator.ts
  packages/exchange/src/pods/demand/demand.controller.ts
  packages/exchange/src/pods/demand/demand.entity.ts
  packages/exchange/src/pods/demand/demand.service.ts
  packages/exchange/src/pods/order-book/order-book.controller.ts
  packages/exchange/src/pods/order/order.controller.ts
  packages/exchange/src/pods/supply/supply.controller.ts
  packages/exchange/src/pods/supply/supply.entity.ts
  packages/exchange/src/pods/supply/supply.module.ts
  packages/exchange/src/pods/supply/supply.service.ts
  packages/exchange/src/pods/trade/trade.controller.ts
  packages/exchange/src/pods/transfer/create-withdrawal.dto.ts
  packages/exchange/src/pods/transfer/transfer.controller.ts
  packages/exchange/src/pods/transfer/transfer.service.ts
  packages/exchange/src/utils/validationHelpers.ts
  packages/exchange/test/api-orders.e2e-spec.ts
  packages/exchange/test/deposits-withdrawals.e2e-spec.ts
  packages/exchange/test/exchange.ts
  packages/migrations/config/seed.sql
  packages/origin-backend-client-mocks/src/UserClientMock.ts
  packages/origin-backend-client/src/UserClient.ts
  packages/origin-backend-core/package.json
  packages/origin-backend-core/src/LoggedInUser.ts
  packages/origin-backend-core/src/RolesDecorator.ts
  packages/origin-backend-core/src/RolesGuard.ts
  packages/origin-backend-core/src/User.ts
  packages/origin-backend-core/src/UserDecorator.ts
  packages/origin-backend-core/src/index.ts
  packages/origin-backend/src/auth/jwt.strategy.ts
  packages/origin-backend/src/pods/admin/admin.controller.ts
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
  packages/origin-backend/src/pods/configuration/configuration.controller.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.service.ts
  packages/origin-backend/src/pods/user/index.ts
  packages/origin-backend/src/pods/user/user.controller.ts
  packages/origin-backend/src/pods/user/user.entity.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
  packages/origin-backend/tsconfig.build.json
  packages/origin-ui-core/src/components/Account/UserRegister.tsx
  packages/origin-ui-core/src/components/AdminUserForm.tsx
  packages/origin-ui-core/src/components/Device.tsx
  packages/origin-ui-core/src/components/ProducingDeviceTable.tsx
Labels: enhancement

#980 chore(origin-backend): update migrations
  packages/origin-backend/migrations/1588836930945-UserStatusAndAutoPublish.ts
  packages/origin-backend/src/pods/user/user.entity.ts
Labels: bug

#982 fix(migrations): remove autopublish from seed.sql
  packages/migrations/config/seed.sql
  packages/origin-backend-utils/package.json
Labels: bug

#976 Certified smart meter readings
  packages/device-registry/src/blockchain-facade/ProducingDevice.ts
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/test/Issuer.test.ts
  packages/localization/src/languages/en.json
  packages/localization/src/languages/pl.json
  packages/migrations/config/seed.sql
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client-mocks/src/DeviceClientMock.ts
  packages/origin-backend-client/src/DeviceClient.ts
  packages/origin-backend-core/src/Device.ts
  packages/origin-backend/migrations/1588841435583-DeviceRmLastSmRead.ts
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
  packages/origin-backend/src/pods/certificate/certification-request.entity.ts
  packages/origin-backend/src/pods/certificate/index.ts
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.entity.ts
  packages/origin-backend/src/pods/device/device.service.ts
  packages/origin-backend/src/pods/user/user.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
  packages/origin-ui-core/src/__tests__/unit/ProducingDeviceTable.test.tsx
  packages/origin-ui-core/src/__tests__/utils/helpers.tsx
  packages/origin-ui-core/src/components/CertificationRequestsTable.tsx
  packages/origin-ui-core/src/components/ProducingDeviceDetailView.tsx
  packages/origin-ui-core/src/components/ProducingDeviceTable.tsx
  packages/solar-simulator/src/consumerService.ts
  packages/solar-simulator/src/workers/mockReadingsWorker.ts
Labels: enhancement

#1009 fix(origin-backend): fix issues with registering/approving devices
  packages/origin-backend/src/pods/device/device.controller.ts
  packages/origin-backend/src/pods/device/device.service.ts
Labels: bug

#1010 fix: set REGISTRATION_MESSAGE_TO_SIGN in Heroku UI deployment script
  provision-heroku-origin.sh
Labels: bug

#1006 feat: Claiming in the name of beneficiary
  packages/issuer/contracts/ERC1888/IERC1888.sol
  packages/issuer/contracts/Registry.sol
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/issuer/src/test/Certificate.test.ts
  packages/origin-ui-core/src/components/CertificateDetailView.tsx
  packages/origin-ui-core/src/components/CertificateTable.tsx
  packages/origin-ui-core/src/components/Modal/ClaimCertificateBulkModal.tsx
  packages/origin-ui-core/src/components/Modal/ClaimModal.tsx
  packages/origin-ui-core/src/features/certificates/actions.ts
  packages/origin-ui-core/src/features/certificates/sagas.ts
Labels: enhancement

#1015 fix(origin-backend): device files migrations
  packages/origin-backend/migrations/1589357904074-DeviceFilesType.ts
  packages/origin-backend/src/pods/device/device.entity.ts
Labels: bug

#1016 fix: fixate tslib version to 1.11.2 to avoid typeorm issue
  packages/exchange/package.json
  packages/migrations/deployment/migrations/canary/Dockerfile
  packages/origin-backend-app/package.json
  packages/origin-backend/package.json
  yarn.lock
Labels: bug

#1017 Fix invalid type when query for Certification Request record
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
Labels: bug

#1018 Fix: Loading ProductionDevice Details View
  packages/device-registry/src/test/DeviceFacade.test.ts
  packages/origin-backend-core/src/Device.ts
  packages/origin-backend/migrations/1589378838360-FilesEmptyArray.ts
  packages/origin-backend/src/pods/device/device.entity.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-backend/test/device.e2e-spec.ts
  packages/origin-backend/test/organization.e2e-spec.ts
Labels: bug

#1056 Fix account data return values
  packages/exchange/package.json
  packages/exchange/src/pods/account-balance/account-balance.service.spec.ts
  packages/exchange/src/pods/account-balance/account-balance.service.ts
  packages/exchange/test/api-orders.e2e-spec.ts
Labels: bug

#1026 Fix: Private Certificate Ownership commitments authorization
  packages/issuer/src/blockchain-facade/Certificate.ts
  packages/issuer/src/blockchain-facade/PreciseProofEntity.ts
  packages/issuer/src/test/Certificate.test.ts
  packages/issuer/src/test/MockCertificate.ts
  packages/origin-backend-client-mocks/src/CertificateClientMock.ts
  packages/origin-backend-client-mocks/src/index.ts
  packages/origin-backend-client/src/CertificateClient.ts
  packages/origin-backend-core/src/Certificate.ts
  packages/origin-backend/migrations/1589560577844-CertificateRequestor.ts
  packages/origin-backend/src/pods/certificate/certificate-watcher.service.ts
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certificate.entity.ts
  packages/origin-backend/src/pods/certificate/certificate.module.ts
  packages/origin-backend/src/pods/certificate/certificate.service.ts
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
  packages/origin-backend/test/certificate.e2e-spec.ts
  packages/origin-backend/test/origin-backend.ts
Labels: enhancement

#1058 Request certificates with organization deposit account as default
  packages/exchange/src/pods/account/account.controller.ts
  packages/issuer/contracts/Issuer.sol
  packages/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/issuer/src/test/Issuer.test.ts
  packages/migrations/tsconfig.build.json
  packages/origin-backend/src/pods/certificate/certification-request-watcher.service.ts
  packages/origin-ui-core/src/components/CertificateTable.tsx
  packages/origin-ui-core/src/features/certificates/sagas.ts
  yarn.lock
Labels: enhancement

#1084 Revert "fix(deps): update dependency @date-io/moment to v2"
  packages/origin-ui-core/package.json
  renovate.json
  yarn.lock
Labels: bug

#1085 Disallow creating certification requests for non-Active devices
  packages/origin-backend/src/pods/certificate/certificate.controller.ts
  packages/origin-backend/src/pods/certificate/certification-request.service.ts
  packages/origin-backend/test/certification-request.e2e-spec.ts
  packages/origin-ui-core/src/components/ProducingDeviceTable.tsx
  yarn.lock
Labels: bug

#1088 fix: endpoint for fetching invitations for an organization
  packages/origin-backend-client/src/OrganizationClient.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/test/organization.e2e-spec.ts
Labels: bug

#1093 Inviting user to organization - Define the Role
  packages/localization/src/languages/en.json
  packages/origin-backend-client-mocks/src/OrganizationClientMock.ts
  packages/origin-backend-client/src/OrganizationClient.ts
  packages/origin-backend-core/src/OrganizationInvitation.ts
  packages/origin-backend/migrations/1590671118755-OrganizationInvitationRole.ts
  packages/origin-backend/src/index.ts
  packages/origin-backend/src/pods/organization/organization-invitation.entity.ts
  packages/origin-backend/src/pods/organization/organization-invitation.service.ts
  packages/origin-backend/src/pods/organization/organization.controller.ts
  packages/origin-backend/src/pods/organization/organization.entity.ts
  packages/origin-backend/src/pods/organization/organization.module.ts
  packages/origin-ui-core/src/components/Organization/OrganizationInvite.tsx
Labels: enhancement

#1095 fix(exchange): correct logged in user id
  packages/exchange/src/pods/order-book/order-book.controller.ts
  packages/exchange/src/pods/order/order.controller.ts
  packages/exchange/src/pods/trade/trade.controller.ts
  packages/exchange/test/api-deposits.e2e-spec.ts
  packages/exchange/test/api-orders.e2e-spec.ts
  packages/exchange/test/api-trades.e2e-spec.ts
  packages/exchange/test/bundles.e2e-spec.ts
  packages/exchange/test/demand.e2e-spec.ts
  packages/exchange/test/deposits-auto-post-for-sale.e2e-spec.ts
  packages/exchange/test/deposits-withdrawals.e2e-spec.ts
  packages/exchange/test/exchange.ts
  packages/exchange/test/orderbook.e2e-spec.ts
Labels: bug

#1097 Release to master
  packages/device-registry/CHANGELOG.md
  packages/device-registry/package.json
  packages/exchange-core/CHANGELOG.md
  packages/exchange-core/package.json
  packages/exchange-token-account/CHANGELOG.md
  packages/exchange-token-account/package.json
  packages/exchange/CHANGELOG.md
  packages/exchange/package.json
  packages/issuer/CHANGELOG.md
  packages/issuer/package.json
  packages/localization/CHANGELOG.md
  packages/localization/package.json
  packages/migrations/CHANGELOG.md
  packages/migrations/package.json
  packages/origin-backend-app/CHANGELOG.md
  packages/origin-backend-app/package.json
  packages/origin-backend-client-mocks/CHANGELOG.md
  packages/origin-backend-client-mocks/package.json
  packages/origin-backend-client/CHANGELOG.md
  packages/origin-backend-client/package.json
  packages/origin-backend-core/CHANGELOG.md
  packages/origin-backend-core/package.json
  packages/origin-backend-utils/CHANGELOG.md
  packages/origin-backend-utils/package.json
  packages/origin-backend/CHANGELOG.md
  packages/origin-backend/package.json
  packages/origin-ui-core/CHANGELOG.md
  packages/origin-ui-core/package.json
  packages/origin-ui/CHANGELOG.md
  packages/origin-ui/package.json
  packages/solar-simulator/CHANGELOG.md
  packages/solar-simulator/package.json
  packages/utils-general/CHANGELOG.md
  packages/utils-general/package.json
Labels: release
