Repository energywebfoundation/origin, pull requests merged in 2021-11, with the labels that each got.

#3090 feat/edit device page
  packages/ui/libs/device/data/src/fetching/deviceDetail.ts
  packages/ui/libs/device/data/src/fetching/deviceTypes.ts
  packages/ui/libs/device/data/src/fetching/fuelTypes.ts
  packages/ui/libs/device/data/src/handlers/editDevice.ts
  packages/ui/libs/device/data/src/handlers/index.ts
  packages/ui/libs/device/logic/src/editDevice/confirmModal.ts
  packages/ui/libs/device/logic/src/editDevice/formConfig.ts
  packages/ui/libs/device/logic/src/editDevice/index.ts
  packages/ui/libs/device/logic/src/index.ts
  packages/ui/libs/device/logic/src/myDeviceCard/myDeviceCard.ts
  packages/ui/libs/device/logic/src/myDeviceCard/types.ts
  packages/ui/libs/device/view/src/DeviceApp.tsx
  packages/ui/libs/device/view/src/containers/card/MyDeviceCardHeader/MyDeviceCardHeader.effects.ts
  packages/ui/libs/device/view/src/containers/card/MyDeviceCardHeader/MyDeviceCardHeader.styles.ts
  packages/ui/libs/device/view/src/containers/card/MyDeviceCardHeader/MyDeviceCardHeader.tsx
  packages/ui/libs/device/view/src/containers/modal/ConfirmEditModal/ConfirmEditModal.effects.ts
  packages/ui/libs/device/view/src/containers/modal/ConfirmEditModal/ConfirmEditModal.tsx
  packages/ui/libs/device/view/src/containers/modal/ConfirmEditModal/index.ts
  packages/ui/libs/device/view/src/containers/modal/DeviceModalsCenter.tsx
  packages/ui/libs/device/view/src/context/modals/reducer.ts
  packages/ui/libs/device/view/src/context/modals/types.ts
  packages/ui/libs/device/view/src/pages/EditDevicePage/EditDevicePage.effects.ts
  packages/ui/libs/device/view/src/pages/EditDevicePage/EditDevicePage.styles.ts
  packages/ui/libs/device/view/src/pages/EditDevicePage/EditDevicePage.tsx
  packages/ui/libs/device/view/src/pages/EditDevicePage/index.ts
  packages/ui/libs/ui/core/src/components/layout/UsernameAndOrg/UsernameAndOrg.tsx
  packages/ui/libs/ui/core/src/components/modal/ModalTextContent/ModalTextContent.tsx
  packages/ui/libs/ui/core/src/components/text/TextWithPendingDot/TextWithPendingDot.tsx
  packages/ui/libs/ui/localization/src/languages/en.json
Labels: feature, UI

#3091 chore/admin-auth fixes
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/libs/exchange/logic/src/marketTables/sellOffers.tsx
  packages/ui/libs/organization/data/src/fetching/index.ts
  packages/ui/libs/organization/data/src/handlers/index.ts
  packages/ui/libs/organization/logic/src/all-organizations/index.ts
  packages/ui/libs/organization/logic/src/all-organizations/types.ts
  packages/ui/libs/organization/logic/src/index.ts
  packages/ui/libs/organization/logic/src/menu/menu.ts
  packages/ui/libs/organization/view/src/OrganizationApp.tsx
  packages/ui/libs/organization/view/src/pages/AllOrganizationsPage/AllOrganizationsPage.tsx
  packages/ui/libs/organization/view/src/pages/AllOrganizationsPage/index.ts
  packages/ui/libs/organization/view/src/pages/index.ts
  packages/ui/libs/ui/core/src/containers/TableComponent/TableComponent.types.ts
  packages/ui/libs/ui/localization/src/languages/en.json
  packages/ui/libs/user/data/src/fetching/allOrganizations.ts
  packages/ui/libs/user/data/src/fetching/index.ts
  packages/ui/libs/user/data/src/handlers/approveOrg.ts
  packages/ui/libs/user/data/src/handlers/index.ts
  packages/ui/libs/user/logic/src/admin/allOrganizations.ts
  packages/ui/libs/user/logic/src/admin/index.ts
  packages/ui/libs/user/logic/src/auth/login.tsx
  packages/ui/libs/user/logic/src/auth/register.tsx
  packages/ui/libs/user/logic/src/menu/getAdminMenu.ts
  packages/ui/libs/user/view/src/AdminApp.tsx
  packages/ui/libs/user/view/src/pages/AdminAllOrganizationsPage/AdminAllOrganizationsPage.effects.tsx
  packages/ui/libs/user/view/src/pages/AdminAllOrganizationsPage/AdminAllOrganizationsPage.tsx
  packages/ui/libs/user/view/src/pages/AdminAllOrganizationsPage/index.ts
  packages/ui/libs/user/view/src/pages/index.ts
Labels: enhancement, UI

#3093 Update ordering and spacing
  docs/traceability.md
  docs/traceability/packages/issuer.md
Labels: documentation

#3117 chore/webpack bundle analyzer
  packages/ui/libs/certificate/data/src/fetching/getBlockchainCertificate.ts
  packages/ui/libs/certificate/data/src/handlers/retireCertificate.ts
  packages/ui/package.json
  packages/ui/webpack.config.js
Labels: enhancement

#3119 chore/react router update
  common/config/rush/pnpm-lock.yaml
  packages/ui/apps/origin-ui/src/components/App/App.tsx
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/libs/ui/core/package.json
  packages/ui/libs/ui/utils/package.json
  packages/ui/libs/user/data/src/fetching/user.ts
  packages/ui/libs/user/logic/src/layout/getTopbarButtonList.tsx
  packages/ui/libs/user/logic/src/layout/index.ts
  packages/ui/package.json
Labels: dependencies

#3146 feat/allow markerprops
  packages/ui/libs/ui/core/src/components/layout/GenericMap/GenericMap.effects.ts
  packages/ui/libs/ui/core/src/components/layout/GenericMap/GenericMap.tsx
Labels: enhancement, UI

#3172 fix/remove expired tokens
  common/config/rush/pnpm-lock.yaml
  packages/ui/apps/origin-ui/src/hooks/useInterceptors.ts
Labels: bug, UI
