Repository energywebfoundation/origin, pull requests merged in 2021-09, with the labels that each got.

#2838 docs/cards components
  packages/ui/libs/ui/core/src/components/card/CardWithImage/CardWithImage.stories.tsx
  packages/ui/libs/ui/core/src/components/card/CardWithImage/CardWithImage.styles.ts
  packages/ui/libs/ui/core/src/components/card/CardWithImage/CardWithImage.tsx
  packages/ui/libs/ui/core/src/components/card/HorizontalCard/HorizontalCard.stories.tsx
  packages/ui/libs/ui/core/src/components/card/HorizontalCard/HorizontalCard.tsx
  packages/ui/libs/ui/core/src/components/images/ImageWithHoverText/ImageWithHoverText.styles.ts
Labels: documentation

#2848 feat/table enhancements
  packages/ui/libs/certificate/data/src/handlers/pendingCertificates.ts
  packages/ui/libs/certificate/logic/src/approved/approved.tsx
  packages/ui/libs/certificate/view/src/pages/PendingPage/PendingPage.effects.tsx
  packages/ui/libs/device/data/src/handlers/pendingDevices.ts
  packages/ui/libs/device/view/src/pages/PendingPage/PendingPage.effects.tsx
  packages/ui/libs/exchange/data/src/fetching/myBundles.ts
  packages/ui/libs/exchange/data/src/handlers/removeOrder.ts
  packages/ui/libs/exchange/logic/src/createBundle/createBundle.tsx
  packages/ui/libs/exchange/view/src/containers/modals/OrderDetails/OrderDetails.effects.ts
  packages/ui/libs/exchange/view/src/containers/my-orders/AsksTable/AsksTable.effects.tsx
  packages/ui/libs/exchange/view/src/containers/my-orders/BidsTable/BidsTable.effects.tsx
  packages/ui/libs/exchange/view/src/pages/MyBundlesPage/MyBundlesPage.effects.tsx
  packages/ui/libs/exchange/view/src/pages/SupplyPage/SupplyPage.effects.tsx
  packages/ui/libs/organization/data/src/handlers/approveOrg.ts
  packages/ui/libs/organization/data/src/handlers/receivedInvitationsHandlers.ts
  packages/ui/libs/organization/data/src/handlers/removeOrgMember.ts
  packages/ui/libs/organization/data/src/handlers/updateOrgMemberRole.ts
  packages/ui/libs/organization/view/src/containers/modals/ChangeMemberRole/ChangeMemberRole.effects.ts
  packages/ui/libs/organization/view/src/pages/AllOrganizationsPage/AllOrganizationsPage.effects.tsx
  packages/ui/libs/organization/view/src/pages/InvitationsPage/InvitationsPage.effects.tsx
  packages/ui/libs/organization/view/src/pages/MembersPage/MembersPage.effects.tsx
  packages/ui/libs/ui/core/src/components/table/TableComponentActions/TableComponentActions.tsx
  packages/ui/libs/ui/core/src/containers/TableComponent/TableComponent.styles.ts
  packages/ui/libs/ui/core/src/containers/TableComponent/TableComponent.types.ts
  packages/ui/libs/user/view/src/pages/AdminUsersPage/AdminUsersPage.effects.tsx
Labels: bug, enhancement, UI

#2849 fix/routes config
  packages/ui/apps/origin-ui/src/components/App/App.tsx
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.tsx
  packages/ui/libs/organization/data/src/handlers/orgRegister.ts
  packages/ui/libs/organization/data/src/handlers/receivedInvitationsHandlers.ts
  packages/ui/libs/organization/data/src/handlers/registerIRec.ts
  packages/ui/libs/organization/view/src/containers/modals/ChangeMemberRole/ChangeMemberRole.effects.ts
  packages/ui/libs/organization/view/src/containers/modals/IRecConnectOrRegister/IRecConnectOrRegister.effects.ts
  packages/ui/libs/organization/view/src/containers/modals/IRecRegisteredThankYou/IRecRegisteredThankYou.effects.ts
  packages/ui/libs/organization/view/src/containers/modals/RegisterThankYou/RegisterThankYou.effects.ts
  packages/ui/libs/organization/view/src/containers/modals/RoleChanged/RoleChanged.effects.tsx
  packages/ui/libs/user/data/src/handlers/pendingInvitationHandlers.ts
  packages/ui/libs/user/data/src/handlers/userLogin.ts
  packages/ui/libs/user/view/src/containers/modals/CreateExchangeAddress/CreateExchangeAddress.effects.ts
  packages/ui/libs/user/view/src/containers/modals/LoginRegisterOrg/LoginRegisterOrg.effects.ts
  packages/ui/libs/user/view/src/containers/modals/PendingInvitation/PendingInvitation.effects.ts
  packages/ui/libs/user/view/src/containers/modals/RoleChanged/RoleChanged.effects.tsx
Labels: bug, UI

#2891 feat/metamask block
  common/config/rush/pnpm-lock.yaml
  packages/api-clients/react-query/origin-backend/src/postGeneration.ts
  packages/devices/origin-device-registry-api/tsconfig.json
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/libs/certificate/data/src/fetching/deviceImages.ts
  packages/ui/libs/certificate/data/src/fetching/file.ts
  packages/ui/libs/certificate/data/src/fetching/index.ts
  packages/ui/libs/certificate/view/src/containers/action/BlockchainTransferAction/BlockchainTransferAction.tsx
  packages/ui/libs/certificate/view/src/containers/action/DepositAction/DepositAction.tsx
  packages/ui/libs/certificate/view/src/containers/action/RetireAction/RetireAction.tsx
  packages/ui/libs/certificate/view/src/containers/carousel/DetailViewCarousel/DetailViewCarousel.tsx
  packages/ui/libs/certificate/view/src/containers/carousel/DeviceImagesCarousel/DeviceImagesCarousel.effects.ts
  packages/ui/libs/certificate/view/src/containers/carousel/DeviceImagesCarousel/DeviceImagesCarousel.tsx
  packages/ui/libs/certificate/view/src/containers/carousel/DeviceMapCarousel/DeviceMapCarousel.styles.ts
  packages/ui/libs/certificate/view/src/containers/carousel/DeviceMapCarousel/DeviceMapCarousel.tsx
  packages/ui/libs/certificate/view/src/pages/BlockchainInboxPage/BlockchainInboxPage.tsx
  packages/ui/libs/device/view/src/containers/carousel/DeviceImagesCarousel/DeviceImagesCarousel.tsx
  packages/ui/libs/organization/view/src/pages/CreateBeneficiaryPage/CreateBeneficiaryPage.styles.ts
  packages/ui/libs/ui/blockchain/src/components/ConnectMetamask/ConnectMetamask.styles.ts
  packages/ui/libs/ui/blockchain/src/components/ConnectMetamask/ConnectMetamask.tsx
  packages/ui/libs/ui/blockchain/src/components/ConnectMetamask/index.ts
  packages/ui/libs/ui/blockchain/src/components/index.ts
  packages/ui/libs/ui/blockchain/src/hoc.tsx
  packages/ui/libs/ui/blockchain/src/theme.d.ts
  packages/ui/libs/ui/core/src/components/images/ImagesCarousel/ImagesCarousel.effects.ts
  packages/ui/libs/ui/core/src/components/images/ImagesCarousel/ImagesCarousel.tsx
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.spec.tsx
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.styles.ts
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.tsx
  packages/ui/libs/user/view/src/containers/blockchain/OrganizationBlockchainAddress/OrganizationBlockchainAddress.tsx
  packages/ui/libs/user/view/src/pages/ProfilePage/ProfilePage.tsx
  packages/ui/package.json
Labels: enhancement, UI

#2894 feat/view market redirect
  packages/ui/libs/exchange/logic/src/index.ts
  packages/ui/libs/exchange/logic/src/marketFilters/regions.ts
  packages/ui/libs/exchange/logic/src/marketTables/sellOffers.tsx
  packages/ui/libs/exchange/logic/src/utils/index.ts
  packages/ui/libs/exchange/logic/src/utils/prepareRegionsOptions.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/getDeviceTypeOption.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/getFuelTypeOption.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/getGridOperatorOption.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/getRegionsOption.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/getSubregionOption.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/index.ts
  packages/ui/libs/exchange/logic/src/viewMarketRedirect/types.ts
  packages/ui/libs/exchange/view/src/containers/my-orders/AsksTable/AsksTable.effects.tsx
  packages/ui/libs/exchange/view/src/containers/my-orders/BidsTable/BidsTable.effects.tsx
  packages/ui/libs/exchange/view/src/pages/ViewMarketPage/ViewMarketPage.effects.tsx
  packages/ui/libs/exchange/view/src/reducer/MarketFiltersReducer.ts
  packages/ui/libs/ui/utils/src/formatters/powerFormatter.ts
Labels: enhancement, UI

#2897 fix/ui pre-release hotfix
  .github/workflows/release.yml
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/libs/certificate/data/src/fetching/certificateToImport.ts
  packages/ui/libs/device/data/src/fetching/deviceFirstImage.ts
  packages/ui/libs/device/data/src/handlers/registerDevice.ts
  packages/ui/libs/exchange/logic/src/utils/getBundleEnergyShares.ts
  packages/ui/libs/exchange/view/src/containers/bundle-details/SplitContents/SplitContents.tsx
  packages/ui/libs/organization/view/src/pages/MembersPage/MembersPage.effects.tsx
  packages/ui/libs/ui/core/.babelrc
  packages/ui/libs/ui/core/src/components/card/CardWithImage/CardWithImage.styles.ts
  packages/ui/libs/ui/core/src/components/list/GenericItemsList/GenericItemsList.tsx
Labels: bug, UI

#2904 feat(issuer): Operator approval check function
  packages/traceability/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/traceability/issuer/test/CertificateUtils.test.ts
Labels: enhancement

#2929 feat/autofill exchange options
  common/config/rush/pnpm-lock.yaml
  packages/ui/apps/origin-ui/src/components/App/App.styles.ts
  packages/ui/libs/exchange/data/src/fetching/orderbook.ts
  packages/ui/libs/exchange/data/src/utils.ts
  packages/ui/libs/exchange/logic/src/marketFilters/deviceType.ts
  packages/ui/libs/exchange/view/src/containers/market/MarketFilters/MarketFilters.effects.ts
  packages/ui/libs/exchange/view/src/containers/market/OneTimePurchase/OneTimePurchase.effects.ts
  packages/ui/libs/exchange/view/src/containers/market/RepeatedPurchase/RepeatedPurchase.effects.ts
  packages/ui/libs/exchange/view/src/pages/MyOrdersPage/MyOrdersPage.tsx
  packages/ui/libs/exchange/view/src/pages/ViewMarketPage/ViewMarketPage.effects.tsx
  packages/ui/libs/ui/core/src/components/list/ListActionsBlock/ListActionsBlock.effects.ts
  packages/ui/libs/ui/core/src/components/list/ListActionsBlock/ListActionsBlock.tsx
Labels: enhancement, UI

#2930 feat/expanded asks
  packages/ui/libs/exchange/data/src/cached/cachedDeviceTypes.ts
  packages/ui/libs/exchange/data/src/cached/index.ts
  packages/ui/libs/exchange/data/src/fetching/assetById.ts
  packages/ui/libs/exchange/data/src/fetching/iRecDeviceById.ts
  packages/ui/libs/exchange/data/src/fetching/index.ts
  packages/ui/libs/exchange/logic/src/marketTables/expandedAsksRow.ts
  packages/ui/libs/exchange/logic/src/marketTables/index.ts
  packages/ui/libs/exchange/logic/src/marketTables/tradingView.tsx
  packages/ui/libs/exchange/logic/src/marketTables/types.ts
  packages/ui/libs/exchange/logic/src/utils/getOwnedOrderStyles.ts
  packages/ui/libs/exchange/view/src/containers/orderbook/ExpandedAsksRow/ExpandedAsksRow.effects.ts
  packages/ui/libs/exchange/view/src/containers/orderbook/ExpandedAsksRow/ExpandedAsksRow.tsx
  packages/ui/libs/exchange/view/src/containers/orderbook/ExpandedAsksRow/index.ts
  packages/ui/libs/exchange/view/src/containers/orderbook/TradingView/TradingView.effects.tsx
  packages/ui/libs/exchange/view/src/containers/orderbook/TradingView/TradingView.tsx
  packages/ui/libs/exchange/view/src/context/asks/index.ts
  packages/ui/libs/exchange/view/src/context/asks/provider.tsx
  packages/ui/libs/exchange/view/src/context/index.ts
  packages/ui/libs/ui/core/src/components/table/TableComponentRow/TableComponentRow.effects.ts
  packages/ui/libs/ui/core/src/components/table/TableComponentRow/TableComponentRow.tsx
  packages/ui/libs/ui/core/src/containers/TableComponent/TableComponent.types.ts
  packages/ui/libs/ui/localization/src/languages/en.json
Labels: enhancement, UI

#2931 fix/asks location filtering
  packages/apps/origin-backend-irec-app/src/integration/external-device.service.ts
  packages/ui/libs/device/data/src/fetching/deviceFirstImage.ts
  packages/ui/libs/exchange/logic/src/utils/prepareSubRegionsOptions.ts
Labels: bug

#2719 feat(exchange-irec): Export from Exchange to I-REC
  common/config/rush/pnpm-lock.yaml
  docs/traceability/contracts/ERC1888/ERC1888.md
  docs/traceability/contracts/Issuer.md
  docs/traceability/contracts/Migrations.md
  docs/traceability/contracts/PrivateIssuer.md
  docs/traceability/contracts/Registry.md
  docs/traceability/contracts/RegistryExtended.md
  packages/api-clients/react-query/exchange-irec/src/generateSchema.ts
  packages/apps/origin-backend-app/test/issuer.e2e-spec.ts
  packages/apps/origin-backend-irec-app/src/integration/external-user.service.ts
  packages/apps/origin-backend-irec-app/src/integration/index.ts
  packages/apps/origin-backend-irec-app/src/integration/integration.module.ts
  packages/apps/origin-backend-irec-app/src/origin-app.module.ts
  packages/apps/origin-backend-irec-app/test/smoke.e2e-spec.ts
  packages/devices/origin-device-registry-irec-local-api/src/device/cron/check-device-state.task.ts
  packages/devices/origin-device-registry-irec-local-api/src/device/device.service.ts
  packages/organizations/origin-organization-irec-api/src/beneficiary/beneficiary.module.ts
  packages/organizations/origin-organization-irec-api/src/irec/irec.module.ts
  packages/organizations/origin-organization-irec-api/src/irec/irec.service.ts
  packages/origin-backend/src/app.module.ts
  packages/traceability/issuer-api/src/pods/certification-request/handlers/get-certification-request-by-certificate.handler.ts
  packages/traceability/issuer-irec-api/src/app.module.ts
  packages/traceability/issuer-irec-api/src/pods/certificate/handler/import-irec-certificate.handler.ts
  packages/traceability/issuer-irec-api/src/pods/certification-request/handlers/create-irec-certification-request.handler.ts
  packages/traceability/issuer-irec-api/src/pods/certification-request/handlers/get-all-certification-requests.handler.ts
  packages/traceability/issuer-irec-api/src/pods/certification-request/handlers/get-certification-request-by-certificate.handler.ts
  packages/traceability/issuer-irec-api/src/pods/certification-request/handlers/get-certification-request.handler.ts
  packages/trade/exchange-irec-client/src/generateSchema.ts
  packages/trade/exchange-irec/migrations/1631695298560-ExportedAsset.ts
  packages/trade/exchange-irec/ormconfig-dev.ts
  packages/trade/exchange-irec/ormconfig.ts
  packages/trade/exchange-irec/package.json
  packages/trade/exchange-irec/src/app.module.ts
  packages/trade/exchange-irec/src/export/command/export-asset.command.ts
  packages/trade/exchange-irec/src/export/command/index.ts
  packages/trade/exchange-irec/src/export/dto/export-asset.dto.ts
  packages/trade/exchange-irec/src/export/dto/index.ts
  packages/trade/exchange-irec/src/export/export-accounting.service.ts
  packages/trade/exchange-irec/src/export/export.controller.ts
  packages/trade/exchange-irec/src/export/export.module.ts
  packages/trade/exchange-irec/src/export/exported.entity.ts
  packages/trade/exchange-irec/src/export/handler/export-asset.handler.ts
  packages/trade/exchange-irec/src/export/index.ts
  packages/trade/exchange-irec/src/index.ts
  packages/trade/exchange-irec/test/exchange.ts
  packages/trade/exchange-irec/test/export.e2e-spec.ts
  packages/trade/exchange-irec/test/orderbook.e2e-spec.ts
  packages/trade/exchange/src/interfaces/IExternalUserService.ts
  packages/trade/exchange/src/interfaces/index.ts
  packages/trade/exchange/src/pods/account-balance/handlers/get-account-balance.handler.ts
  packages/trade/exchange/src/pods/account-balance/handlers/index.ts
  packages/trade/exchange/src/pods/account-balance/queries/get-account-balance.query.ts
  packages/trade/exchange/src/pods/account-balance/queries/index.ts
  packages/trade/exchange/test/exchange.ts
Labels: enhancement

#2952 fix(issuer): Make sure that .sol files are contained within the NPM r…
  common/config/rush/pnpm-lock.yaml
  packages/traceability/issuer/package.json
Labels: bug
