Repository energywebfoundation/origin, pull requests merged in 2021-05, with the labels that each got.

#2341 feat(issuer): Smart Contract Improvements
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/traceability/issuer-api/migrations/1619791124674-PrivateIssuer.ts
  packages/traceability/issuer-api/package.json
  packages/traceability/issuer-api/src/pods/blockchain/blockchain-properties.dto.ts
  packages/traceability/issuer-api/src/pods/blockchain/blockchain-properties.entity.ts
  packages/traceability/issuer-api/src/pods/blockchain/blockchain-properties.service.ts
  packages/traceability/issuer-api/src/pods/certificate/certificate.controller.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/claim-certificate.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/listeners/on-chain-certificates.listener.ts
  packages/traceability/issuer-api/test/certificate.e2e-spec.ts
  packages/traceability/issuer-api/test/issuer-api.ts
  packages/traceability/issuer/contracts/ERC1155/Address.sol
  packages/traceability/issuer/contracts/ERC1155/ERC1155.sol
  packages/traceability/issuer/contracts/ERC1155/ERC1155Mintable.sol
  packages/traceability/issuer/contracts/ERC1155/IERC1155.sol
  packages/traceability/issuer/contracts/ERC1155/IERC1155TokenReceiver.sol
  packages/traceability/issuer/contracts/ERC1888/IERC1888.sol
  packages/traceability/issuer/contracts/Issuer.sol
  packages/traceability/issuer/contracts/PrivateIssuer.sol
  packages/traceability/issuer/contracts/Registry.sol
  packages/traceability/issuer/migrations/1_initial.js
  packages/traceability/issuer/package.json
  packages/traceability/issuer/src/blockchain-facade/BlockchainProperties.ts
  packages/traceability/issuer/src/blockchain-facade/Certificate.ts
  packages/traceability/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/traceability/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/traceability/issuer/src/contracts.ts
  packages/traceability/issuer/src/migrate.ts
  packages/traceability/issuer/src/test/Issuer.test.ts
  packages/traceability/issuer/truffle-config.js
  packages/trade/exchange-io-erc1888/src/deposit-watcher/deposit-watcher.service.ts
  packages/trade/exchange-io-erc1888/src/withdrawal-processor/withdrawal-processor.service.ts
  packages/trade/exchange-io-erc1888/test/deposits-auto-post-for-sale.e2e-spec.ts
  packages/trade/exchange-io-erc1888/test/deposits-withdrawals.e2e-spec.ts
  packages/trade/exchange-token-account/contracts/Common.sol
  packages/trade/exchange-token-account/contracts/TestToken.sol
  packages/trade/exchange-token-account/contracts/TokenAccount.sol
  packages/trade/exchange-token-account/package.json
  packages/trade/exchange/test/utils.ts
Labels: enhancement

#2379 feat: Smart contracts upgradeability tests
  .github/workflows/lint-and-test.yml
  common/config/rush/command-line.json
  package.json
  packages/device-registry/package.json
  packages/traceability/issuer-api/test/certificate.e2e-spec.ts
  packages/traceability/issuer/.gitignore
  packages/traceability/issuer/contracts/Issuer.sol
  packages/traceability/issuer/contracts/PrivateIssuer.sol
  packages/traceability/issuer/migrations/1_initial.js
  packages/traceability/issuer/package.json
  packages/traceability/issuer/test/Certificate.test.ts
  packages/traceability/issuer/test/Issuer.test.ts
  packages/traceability/issuer/test/truffle/upgradedContract.ts
  packages/traceability/issuer/test/truffle/upgrades.test.js
  packages/traceability/issuer/truffle-config.js
  packages/traceability/issuer/tsconfig.json
  packages/trade/exchange-core-irec/package.json
  packages/trade/exchange-core/package.json
  packages/trade/exchange-irec/package.json
  packages/trade/exchange-token-account/contracts/TestToken.sol
  packages/trade/exchange-token-account/package.json
  packages/trade/exchange-token-account/test/token-account.test.ts
  packages/trade/exchange/package.json
Labels: documentation, enhancement

#2399 chore(issuer): MythX audit results
  packages/traceability/issuer/.gitignore
  packages/traceability/issuer/.mythx.yml
  packages/traceability/issuer/contracts/Issuer.sol
  packages/traceability/issuer/contracts/Migrations.sol
  packages/traceability/issuer/contracts/PrivateIssuer.sol
  packages/traceability/issuer/contracts/Registry.sol
  packages/traceability/issuer/migrations/1_initial_migration.js
  packages/traceability/issuer/migrations/2_registry_and_issuer.js
  packages/traceability/issuer/package.json
Labels: enhancement

#2402 chore(issuer-api): Emit CertificatePersistedEvent when a certificate …
  packages/traceability/issuer-api/src/pods/certificate/handlers/issue-certificate.handler.ts
Labels: bug, enhancement

#2418 feat: Certificate metadata
  common/config/rush/pnpm-lock.yaml
  packages/traceability/issuer-api/migrations/1621262657405-CertificateMetadata.ts
  packages/traceability/issuer-api/src/pods/certificate/certificate.controller.ts
  packages/traceability/issuer-api/src/pods/certificate/certificate.dto.ts
  packages/traceability/issuer-api/src/pods/certificate/certificate.entity.ts
  packages/traceability/issuer-api/src/pods/certificate/commands/issue-certificate.command.ts
  packages/traceability/issuer-api/src/pods/certificate/commands/issue-certificate.dto.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/issue-certificate.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/utils/index.ts
  packages/traceability/issuer/.mythx.yml
  packages/traceability/issuer/contracts/Issuer.sol
  packages/traceability/issuer/contracts/PrivateIssuer.sol
  packages/traceability/issuer/contracts/Registry.sol
  packages/traceability/issuer/src/blockchain-facade/Certificate.ts
  packages/traceability/issuer/src/blockchain-facade/CertificateUtils.ts
  packages/traceability/issuer/src/blockchain-facade/CertificationRequest.ts
  packages/traceability/issuer/test/Certificate.test.ts
  packages/traceability/issuer/test/Issuer.test.ts
  packages/trade/exchange/test/utils.ts
Labels: enhancement

#2421 fix(origin-ui-core): Fix fetching blockchain events per certificate
  common/config/rush/pnpm-lock.yaml
  packages/ui/origin-ui-core/src/components/certificates/DetailView/CertificateDetailView.tsx
Labels: bug

#2424 chore: use npx in certain commands
  packages/apps/origin-backend-app/package.json
  packages/tools/migrations-irec/package.json
  packages/tools/migrations/package.json
Labels: bug

#2449 chore: update ethers to 5.2.0
  common/config/rush/pnpm-lock.yaml
  packages/apps/origin-backend-app/package.json
  packages/device-registry/package.json
  packages/devices/origin-device-registry-irec-form-api/package.json
  packages/origin-backend-core/package.json
  packages/origin-backend/package.json
  packages/tools/migrations-irec/package.json
  packages/tools/migrations/package.json
  packages/tools/solar-simulator/package.json
  packages/traceability/issuer-api/package.json
  packages/traceability/issuer/package.json
  packages/trade/exchange-io-erc1888/package.json
  packages/trade/exchange-token-account/package.json
  packages/trade/exchange/package.json
  packages/ui/exchange-ui-core/package.json
  packages/ui/origin-ui-core/package.json
  packages/ui/origin-ui-irec-core/package.json
  packages/utils/utils-general/package.json
  renovate.json
Labels: dependencies

#2454 fix(db-schema): Configuration.id definition
  packages/origin-backend/src/pods/configuration/configuration.entity.ts
Labels: bug

#2457 fix(migrations-irec): migrations-irec seed file
  packages/tools/migrations-irec/config/seed.sql
Labels: bug
