Repository energywebfoundation/origin, pull requests merged in 2021-04, with the labels that each got.

#2315 fix(origin-backend): Documents ownership check
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/apps/origin-backend-app/package.json
  packages/device-registry/package.json
  packages/devices/origin-device-registry-irec-form-api/package.json
  packages/origin-backend-core/package.json
  packages/origin-backend/package.json
  packages/origin-backend/src/pods/file/file.service.ts
  packages/tools/migrations-irec/package.json
  packages/tools/migrations/package.json
  packages/tools/solar-simulator/package.json
  packages/traceability/issuer-api/package.json
  packages/traceability/issuer/package.json
  packages/trade/exchange-io-erc1888/package.json
  packages/trade/exchange-token-account/package.json
  packages/trade/exchange/package.json
  packages/ui/exchange-ui-core/package.json
  packages/ui/origin-ui-core/package.json
  packages/ui/origin-ui-irec-core/package.json
  packages/utils/utils-general/package.json
Labels: bug

#2339 fix(issuer-api): Use getRepository when self-updating certificate
  common/config/rush/pnpm-lock.yaml
  packages/traceability/issuer-api/src/pods/certificate/certificate.entity.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/sync-certificate.handler.ts
Labels: bug

#2340 fix(issuer-api): Certificate events syncing
  packages/traceability/issuer-api/src/pods/certificate/certificate.entity.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/bulk-claim-certificates.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/claim-certificate.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/sync-certificate.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/handlers/transfer-certificate.handler.ts
  packages/traceability/issuer-api/src/pods/certificate/listeners/on-chain-certificates.listener.ts
  packages/traceability/issuer-api/test/certificate.e2e-spec.ts
Labels: bug

#2338 chore(docker): docker compose files to start 4 isolated variants of the Origin
  .gitignore
  docker-compose.collective.yml
  docker-compose.yml
  docs/docker.md
  mkdocs.yml
  origin-docker-run.sh
  origin.local.irec.yml
  origin.local.yml
  origin.release.irec.yml
  origin.release.yml
  packages/apps/origin-backend-app/Dockerfile.local
  packages/tools/migrations-irec/Makefile
  packages/tools/migrations-irec/deployment/migrations/canary/Dockerfile.local
  packages/tools/migrations-irec/deployment/migrations/stable/Dockerfile
  packages/tools/migrations-irec/package.json
  packages/tools/migrations/Makefile
  packages/tools/migrations/deployment/migrations/canary/Dockerfile.local
  packages/tools/migrations/deployment/migrations/stable/Dockerfile
  packages/tools/migrations/package.json
  packages/tools/solar-simulator/Dockerfile.local
Labels: enhancement

#2349 chore(docs): Readme update
  README.md
Labels: documentation
