Repository energywebfoundation/origin, pull requests merged in 2021-12, with the labels that each got.

#3174 feat/exchange claim UI
  packages/trade/exchange/src/pods/transfer/dto/index.ts
  packages/trade/exchange/src/pods/transfer/transfer.entity.ts
  packages/ui/libs/certificate/data/src/fetching/claimedCertificates.ts
  packages/ui/libs/certificate/data/src/handlers/claimCertificate.ts
  packages/ui/libs/certificate/data/src/handlers/index.ts
  packages/ui/libs/certificate/logic/src/claims/claimsReport.ts
  packages/ui/libs/certificate/logic/src/detail-view/certificateData.ts
  packages/ui/libs/certificate/logic/src/exchange-inbox/claimAction.ts
  packages/ui/libs/certificate/logic/src/exchange-inbox/index.ts
  packages/ui/libs/certificate/logic/src/exchange-inbox/types.ts
  packages/ui/libs/certificate/view/src/containers/action/ClaimAction/ClaimAction.effects.ts
  packages/ui/libs/certificate/view/src/containers/action/ClaimAction/ClaimAction.tsx
  packages/ui/libs/certificate/view/src/containers/action/ClaimAction/index.ts
  packages/ui/libs/certificate/view/src/containers/action/RetireAction/RetireAction.styles.ts
  packages/ui/libs/certificate/view/src/containers/action/RetireAction/RetireAction.tsx
  packages/ui/libs/certificate/view/src/containers/action/index.ts
  packages/ui/libs/certificate/view/src/containers/detail-view/CertificateDetails/CertificateDetails.effects.tsx
  packages/ui/libs/certificate/view/src/containers/detail-view/CertificateDetails/CertificateDetails.tsx
  packages/ui/libs/certificate/view/src/pages/ClaimsReportPage/ClaimsReportPage.effects.tsx
  packages/ui/libs/certificate/view/src/pages/ExchangeInboxPage/ExchangeInboxPage.effects.tsx
  packages/ui/libs/device/logic/src/requestCertificates/requestCertificatesLogic.ts
  packages/ui/libs/ui/core/src/components/list/ListActionsBlock/ListActionsBlock.effects.ts
  packages/ui/libs/ui/core/src/components/list/ListActionsBlock/ListActionsBlock.tsx
  packages/ui/libs/ui/localization/src/languages/en.json
  packages/ui/libs/user/view/src/pages/SettingsPage/SettingsPage.tsx
Labels: feature, UI

#3145 Wpurdum/exchange module documentation
  docs/backend.md
  docs/certificate-guides/exchange-inbox.md
  docs/device-guides/device-guide-intro.md
  docs/device-registry.md
  docs/device-registry/device-registry-api.md
  docs/exchange-guides/exchange-guide-intro.md
  docs/images/exchangeForwarding.png
  docs/index.md
  docs/organization-guides/org-guide-intro.md
  docs/packages.md
  docs/traceability.md
  docs/traceability/packages/issuer-api.md
  docs/traceability/packages/issuer.md
  docs/trade.md
  docs/trade/exchange-core.md
  docs/trade/exchange-io-erc1888.md
  docs/trade/exchange-token-account.md
  docs/trade/exchange.md
  docs/trade/matching-criteria.md
  docs/user-guide-certificate.md
  docs/user-guide-device-management.md
  docs/user-guide-exchange.md
  docs/user-guide-glossary.md
  docs/user-guide-onboarding.md
  docs/user-guide-organization.md
  mkdocs.yml
Labels: documentation

#3197 feat/blockchain account options
  common/config/rush/pnpm-lock.yaml
  packages/trade/exchange-io-erc1888/src/withdrawal-processor/withdrawal-processor.service.ts
  packages/trade/exchange/migrations/1639052544086-ClaimAddress.ts
  packages/trade/exchange/src/pods/transfer/dto/request-claim.dto.ts
  packages/trade/exchange/src/pods/transfer/transfer.entity.ts
  packages/trade/exchange/src/pods/transfer/transfer.service.ts
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/libs/certificate/data/src/fetching/claimedCertificates.ts
  packages/ui/libs/certificate/data/src/handlers/blockchainTransferCertificate.ts
  packages/ui/libs/certificate/data/src/handlers/claimCertificate.ts
  packages/ui/libs/certificate/data/src/handlers/depositCertificate.ts
  packages/ui/libs/certificate/data/src/handlers/retireCertificate.ts
  packages/ui/libs/certificate/view/src/pages/ExchangeInboxPage/ExchangeInboxPage.effects.tsx
  packages/ui/libs/device/data/src/cached/cachedUser.ts
  packages/ui/libs/device/data/src/cached/index.ts
  packages/ui/libs/device/data/src/handlers/requestCertificates.ts
  packages/ui/libs/ui/localization/src/languages/en.json
  packages/ui/libs/user/data/src/cached/cachedUser.ts
  packages/ui/libs/user/data/src/cached/index.ts
  packages/ui/libs/user/data/src/handlers/changeSelfOwnership.ts
  packages/ui/libs/user/data/src/handlers/index.ts
  packages/ui/libs/user/data/src/index.ts
  packages/ui/libs/user/logic/src/account/exchangeDeposit.ts
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.effects.ts
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.spec.tsx
  packages/ui/libs/user/view/src/containers/blockchain/BlockchainAddressesContainer/BlockchainAddressesContainer.tsx
  packages/ui/libs/user/view/src/containers/blockchain/FullSelfOwnershipContainer/FullSelfOwnershipContainer.effects.ts
  packages/ui/libs/user/view/src/containers/blockchain/FullSelfOwnershipContainer/FullSelfOwnershipContainer.styles.tsx
  packages/ui/libs/user/view/src/containers/blockchain/FullSelfOwnershipContainer/FullSelfOwnershipContainer.tsx
  packages/ui/libs/user/view/src/containers/blockchain/FullSelfOwnershipContainer/index.ts
  packages/ui/libs/user/view/src/containers/blockchain/OrganizationBlockchainAddress/OrganizationBlockchainAddress.spec.tsx
  packages/ui/libs/user/view/src/containers/blockchain/OrganizationBlockchainAddress/OrganizationBlockchainAddress.tsx
  packages/ui/libs/user/view/src/containers/blockchain/UserExchangeDepositAddress/UserExchangeDepositAddress.effects.ts
  packages/ui/libs/user/view/src/containers/blockchain/UserExchangeDepositAddress/UserExchangeDepositAddress.spec.tsx
  packages/ui/libs/user/view/src/containers/blockchain/UserExchangeDepositAddress/UserExchangeDepositAddress.styles.tsx
  packages/ui/libs/user/view/src/containers/blockchain/UserExchangeDepositAddress/UserExchangeDepositAddress.tsx
  packages/ui/libs/user/view/src/containers/blockchain/index.ts
Labels: enhancement, UI

#3212 Wpurdum/documentation cleanup
  docs/backend.md
  docs/certificate-guides/blockchain-inbox.md
  docs/certificate-guides/cert-guide-intro.md
  docs/certificate-guides/claims-report.md
  docs/certificate-guides/exchange-inbox.md
  docs/certificate-guides/import-certificate.md
  docs/certificate-guides/requests.md
  docs/device-guides/all-devices.md
  docs/device-guides/device-guide-intro.md
  docs/device-guides/import-device.md
  docs/device-guides/map-view.md
  docs/device-guides/my-devices.md
  docs/device-guides/register-device.md
  docs/device-registry.md
  docs/device-registry/device-registry-api.md
  docs/exchange-guides/all-bundles.md
  docs/exchange-guides/create-bundle.md
  docs/exchange-guides/exchange-guide-intro.md
  docs/exchange-guides/my-bundles.md
  docs/exchange-guides/my-orders.md
  docs/exchange-guides/my-trades.md
  docs/exchange-guides/supply.md
  docs/exchange-guides/view-market.md
  docs/images/certificates/claims-blockchainclaim.png
  docs/images/certificates/claims-exchangewalletclaim.png
  docs/images/certificates/claimsreport-claimfromcertinbox.png
  docs/images/certificates/exchangeinbox-claimtab.png
  docs/images/onboarding/blockchainaddresses-fullselfownership.png
  docs/images/onboarding/onboarding-blockchainaddress.png
  docs/images/onboarding/onboarding-exchangedepositaddress.png
  docs/images/onboarding/onboarding-fullselfownership.png
  docs/index.md
  docs/organization-guides/connect-irec.md
  docs/organization-guides/create-beneficiary.md
  docs/organization-guides/invitations.md
  docs/organization-guides/invite.md
  docs/organization-guides/members.md
  docs/organization-guides/org-guide-intro.md
  docs/traceability.md
  docs/traceability/packages/issuer-api.md
  docs/traceability/packages/issuer.md
  docs/trade/exchange-core.md
  docs/trade/exchange-io-erc1888.md
  docs/trade/exchange-token-account.md
  docs/trade/exchange.md
  docs/user-guide-glossary.md
  docs/user-guide-reg-onboarding.md
  docs/user-guides.md
Labels: documentation

#3223 fix/pre-release bugs
  packages/ui/apps/origin-ui/src/components/App/App.tsx
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.effects.tsx
  packages/ui/apps/origin-ui/src/components/AppContainer/AppContainer.tsx
  packages/ui/apps/origin-ui/src/hooks/useInterceptors.ts
  packages/ui/apps/origin-ui/src/main.tsx
  packages/ui/libs/device/data/src/cached/cachedIRecConnection.ts
  packages/ui/libs/device/data/src/cached/cachedIRecOrg.ts
  packages/ui/libs/device/data/src/cached/index.ts
  packages/ui/libs/device/data/src/index.ts
  packages/ui/libs/device/logic/src/permissions/permissions.ts
  packages/ui/libs/device/logic/src/permissions/types.ts
  packages/ui/libs/device/view/src/pages/MyDevicesPage/MyDevicesPage.effects.ts
  packages/ui/libs/device/view/src/pages/RegisterPage/RegisterPage.effects.ts
  packages/ui/libs/exchange/view/src/containers/bundle-details/SplitContents/SplitContents.effects.ts
  packages/ui/libs/exchange/view/src/containers/bundle-details/SplitContents/SplitContents.tsx
  packages/ui/libs/organization/data/src/cached/cachedIRecConnection.ts
  packages/ui/libs/organization/data/src/cached/cachedIRecOrg.ts
  packages/ui/libs/organization/data/src/cached/cachedUser.ts
  packages/ui/libs/organization/data/src/cached/index.ts
  packages/ui/libs/organization/data/src/index.ts
  packages/ui/libs/organization/logic/src/beneficiaries/form.ts
  packages/ui/libs/organization/logic/src/beneficiaries/index.ts
  packages/ui/libs/organization/logic/src/beneficiaries/permissions.ts
  packages/ui/libs/organization/logic/src/connect-irec/connectForm.ts
  packages/ui/libs/organization/logic/src/permissions/index.ts
  packages/ui/libs/organization/logic/src/permissions/permissions.ts
  packages/ui/libs/organization/logic/src/permissions/types.ts
  packages/ui/libs/organization/view/src/pages/CreateBeneficiaryPage/CreateBeneficiaryPage.effects.tsx
  packages/ui/libs/organization/view/src/pages/CreateBeneficiaryPage/CreateBeneficiaryPage.tsx
  packages/ui/libs/ui/core/src/components/layout/Requirements/Requirements.styles.ts
  packages/ui/libs/ui/core/src/components/layout/Requirements/Requirements.tsx
  packages/ui/libs/ui/localization/src/languages/en.json
  packages/ui/libs/ui/shared-state/src/language/localStorage.ts
  packages/ui/libs/user/data/src/fetching/adminOrganizationById.ts
  packages/ui/libs/user/data/src/fetching/index.ts
  packages/ui/libs/user/data/src/handlers/errorHandler.ts
  packages/ui/libs/user/data/src/handlers/userLogin.ts
  packages/ui/libs/user/logic/src/admin/allOrganizations.ts
  packages/ui/libs/user/logic/src/admin/index.ts
  packages/ui/libs/user/logic/src/admin/organizationView.ts
  packages/ui/libs/user/logic/src/auth/register.tsx
  packages/ui/libs/user/logic/src/menu/getAdminMenu.ts
  packages/ui/libs/user/view/src/AdminApp.tsx
  packages/ui/libs/user/view/src/LoginApp.tsx
  packages/ui/libs/user/view/src/containers/file/DownloadOrgDocs/DownloadOrgDocs.styles.ts
  packages/ui/libs/user/view/src/containers/file/DownloadOrgDocs/DownloadOrgDocs.tsx
  packages/ui/libs/user/view/src/containers/file/DownloadOrgDocs/index.ts
  packages/ui/libs/user/view/src/containers/file/index.ts
  packages/ui/libs/user/view/src/containers/index.ts
  packages/ui/libs/user/view/src/containers/modals/PendingInvitation/PendingInvitation.effects.ts
  packages/ui/libs/user/view/src/containers/modals/RoleChanged/RoleChanged.effects.tsx
  packages/ui/libs/user/view/src/context/modals/reducer.ts
  packages/ui/libs/user/view/src/context/modals/types.ts
  packages/ui/libs/user/view/src/pages/AdminOrganizationViewPage/AdminOrganizationViewPage.effects.ts
  packages/ui/libs/user/view/src/pages/AdminOrganizationViewPage/AdminOrganizationViewPage.styles.ts
  packages/ui/libs/user/view/src/pages/AdminOrganizationViewPage/AdminOrganizationViewPage.tsx
  packages/ui/libs/user/view/src/pages/AdminOrganizationViewPage/index.ts
  packages/ui/libs/user/view/src/pages/LoginPage/LoginPage.effects.ts
  packages/ui/libs/user/view/src/pages/LoginPage/LoginPage.tsx
  packages/ui/libs/user/view/src/pages/index.ts
Labels: bug, UI

#3235 fix/exchange claim beneficiary
  common/config/rush/pnpm-lock.yaml
  packages/ui/libs/certificate/data/src/handlers/claimCertificate.ts
  packages/ui/libs/certificate/logic/src/exchange-inbox/claimAction.ts
  packages/ui/libs/certificate/logic/src/exchange-inbox/types.ts
  packages/ui/libs/certificate/view/src/containers/action/ClaimAction/ClaimAction.effects.ts
  packages/ui/libs/certificate/view/src/containers/action/ClaimAction/ClaimAction.tsx
  packages/ui/libs/device/view/src/containers/card/MyDeviceCardContent/MyDeviceCardContent.tsx
  packages/ui/libs/device/view/src/containers/card/MyDeviceCardHeader/MyDeviceCardHeader.tsx
  packages/ui/libs/organization/logic/src/beneficiaries/permissions.ts
  packages/ui/libs/ui/localization/src/languages/en.json
Labels: enhancement, UI

#3269 docs/ui packages read-me's
  common/config/rush/pnpm-lock.yaml
  packages/ui/apps/origin-ui/src/components/OriginThemeProvider/OriginThemeProvider.tsx
  packages/ui/libs/ui/assets/README.md
  packages/ui/libs/ui/core/.storybook/preview.js
  packages/ui/libs/ui/core/README.md
  packages/ui/libs/ui/localization/README.md
  packages/ui/libs/ui/shared-state/README.md
  packages/ui/libs/ui/theme/README.md
  packages/ui/libs/ui/theme/src/config/themeConfig.ts
  packages/ui/libs/ui/theme/src/utils/createStyleConfig.ts
  packages/ui/libs/ui/utils/README.md
  packages/ui/libs/ui/utils/src/date/DateFormatEnum.ts
  packages/ui/libs/ui/utils/src/date/formatDate.ts
  packages/ui/libs/ui/utils/src/date/index.ts
Labels: documentation, UI

#3274 chore: add docs for partial ui setup
  packages/ui/libs/certificate/view/README.md
  packages/ui/libs/certificate/view/src/index.ts
  packages/ui/libs/device/view/README.md
  packages/ui/libs/device/view/src/index.ts
  packages/ui/libs/exchange/view/README.md
  packages/ui/libs/organization/view/README.md
  packages/ui/libs/organization/view/src/index.ts
  packages/ui/libs/user/view/README.md
Labels: documentation, UI

#3273 add architecture overview and diagram
  docs/architecture.md
  docs/images/panels/origin-architecture.png
  docs/traceability.md
  docs/traceability/packages/issuer.md
  docs/trade/exchange-token-account.md
  docs/user-guide-glossary.md
Labels: documentation

#3277 Spacing fix + notes on getting started
  docs/architecture.md
  docs/backend.md
  docs/device-registry.md
  docs/getting-started.md
  docs/traceability/packages/issuer-api.md
  docs/trade/exchange.md
  mkdocs.yml
Labels: documentation
